### ISSUE TITLE
Please use protected visibility

### ISSUE THREAD

**Issue by dereuromark** [KnpLabs/php-github-api#1010]
Internally, when not using public visibility, please consider going back to protected instead of hardcore private.
This was the case in v2 and allowed us to overwrite and extend where needed in order to get things done.

Right now, in v3 it would require completely copy and pasting the whole repo or forking hard.
Instead we just wanted to add some missing functionality in a very small subset

    /**
     * @return \App\Api\Git\Workflows
     */
    public function workflows(): Workflows
    {
        return new AppWorkflows($this->client); // client is now private and this doesn't work anymore
    }
    
It is commonly a bad practice to close using private on an active library that is to be expected not to be fully-featured and ever-evolving.
The risk on the extension is on the user side, and all stakeholders are absolutely clear about this, even if any BC break is done here.
But it trumps the issue of now having to workaround with a much higher risk of losing other updates and a much higher cost factor on the dev part.

It also doesn't show an upgrade path or solution in the docs or https://github.com/KnpLabs/php-github-api/blob/master/UPGRADE-3.0.md
Maybe there is a possible solution here to switch out parts (class or method) without having to copy paste too much?

**Comment by dereuromark** [comment]
I see now that you exposed it through

    getClient()

which makes my case work again.
I guess my point still stands as a general topic - as there will always be a case where things have to be quickly fixed on project level.

**Comment by acrobat** [comment]
Hi @dereuromark 

> It is commonly a bad practice to close using private on an active library that is to be expected not to be fully-featured and ever-evolving.

We try to be as feature complete as possible and follow up on github api changes. Also we always welcome PR's to add missing functionality and thiese can be merged and released in a short time. There is also functionality in place to allow users to [manually call an endpoint](https://github.com/KnpLabs/php-github-api/blob/master/doc/request_any_route.md) if it's not yet covered by api. This will also help to not be blocked if the specific api not yet included.

> The risk on the extension is on the user side, and all stakeholders are absolutely clear about this, even if any BC break is done here.

Well I think we disagree on this. As the "risk" is not only on the userside but also on our side, if we make any changes to those "extension points" and it breaks the use cases they are using we will get the bugreports. So therefor I like to keep 
the class api as close as possible and just open things up for specific usecases (like the `getClient()` method for example). 

This way we keep the maintenance burden low. But we're open to discuss any needed extensions points, if you have a case we can discuss the validity of it and if needed we open specific parts.
