### ISSUE TITLE
[FR] Get All Pull Requests across all Repositories

### ISSUE THREAD

**Issue by raisonon** [KnpLabs/php-github-api#1021]
Any ideas how to fetch all pull requests per user (without specifying the repository).

As per: https://github.com/KnpLabs/php-github-api/blob/master/doc/pull_requests.md#list-all-pull-requests-per-repository

we have:

```
<?php

$openPullRequests = $client->api('pull_request')->all('ezsystems', 'ezpublish');

```

But we require repository name here. Ideally we could use below:

```
<?php

$openPullRequests = $client->api('pull_request')->all($userName);

```

I have tried this:

`$client->search()->issues("q=author:userName", 'asc', '')`

But it does not show the pullRequests associated to the users repositories, just non-user repositories.

Any ideas on feasibility of this for a new feature?

Thanks

**Comment by acrobat** [comment]
Hi @raisonon, I don't think the github rest api easily support this. But I think you can solve this with a graphql query

```php
$query = <<<QUERY
query { 
  viewer { 
    pullRequests (first: 100) {
    	nodes {
           number, title
        }
     }
  }
}
QUERY;

$pulls = $client->api('graphql')->execute($query);
```

**Comment by raisonon** [comment]
That's best approach - thanks - I've been using the graphql api but didn't realise you can run via this package with: $client->api('graphql')->execute($query);

Fantastic!
