### ISSUE TITLE
[Question] How to detect if used is authenticated or not?

### ISSUE THREAD

**Issue by TomasVotruba** [KnpLabs/php-github-api#1022]
Hi,

thank you for this package. It saves us lot of time and work :+1: 

I'm going through docs and issues and I can't find out, how to detect if used is logged in or not.
I assume something like this should work:

```php
$client->isAuthenticated(): bool
```

But I can't find it. How can I achieve that without wrapping every call in try/catch?	
Thanks

**Comment by TomasVotruba** [comment]
The best solution so far... I hope there is a better one :slightly_smiling_face: 

```php
    public function isAuthenticated(): bool
    {
        /** @var Builder $httpClientBuilder */
        $httpClientBuilder = $this->privatesCaller->callPrivateMethod($this->client, 'getHttpClientBuilder', []);

        /** @var Plugin[] $plugins */
        $plugins = $this->privatesAccessor->getPrivateProperty($httpClientBuilder, 'plugins');
        foreach ($plugins as $plugin) {
            if ($plugin instanceof AuthenticationPlugin) {
                return true;
            }
        }

        return false;
    }
```

**Comment by acrobat** [comment]
I think simplest solution would be to add a `authenticated` properpty (add method) and set the value to true if the user called `$client->authenticate(...);`. Not sure if I miss something that would "break" something 🤔  

Or if we add a extra property on the client builder this would allow us to check the plugin's in the client

```diff
diff --git a/lib/Github/Client.php b/lib/Github/Client.php
index 6ea5072..d2f81b7 100644
--- a/lib/Github/Client.php
+++ b/lib/Github/Client.php
@@ -412,4 +412,9 @@ class Client
     {
         return $this->httpClientBuilder;
     }
+
+    public function isAuthenticated(): bool
+    {
+        return $this->getHttpClientBuilder()->hasPlugin(Authentication::class);
+    }
 }
diff --git a/lib/Github/HttpClient/Builder.php b/lib/Github/HttpClient/Builder.php
index a8713de..e2f7dad 100644
--- a/lib/Github/HttpClient/Builder.php
+++ b/lib/Github/HttpClient/Builder.php
@@ -211,4 +211,16 @@ class Builder
         $this->cachePlugin = null;
         $this->httpClientModified = true;
     }
+
+
+    public function hasPlugin(string $pluginClass): bool
+    {
+        foreach ($this->plugins as $plugin) {
+            if ($plugin instanceof $pluginClass) {
+                return true;
+            }
+        }
+
+        return false;
+    }
 }

```

What do you think @TomasVotruba?

**Comment by TomasVotruba** [comment]
Thanks for sharing!
I actually used exactly similar solution, but then I found out the plugin presence is irrelevant.

The authentication occurs on rest API call, not on authenticate(). The method name is misleading here. It should be named configureCredentials() instead.

**Comment by acrobat** [comment]
You are right, so the best thing to do might be to add a "helper service" in your app which calls a api for the current user (maybe some api that doesn't change that much to minimize the actual calls). If you are not authenticated github will throw an error, so that single helper method will be able to check if the current api client is authenticated or not. I would add some caching on that call so that you don't deplete your github api ratelimit.

**Comment by TomasVotruba** [comment]
> If you are not authenticated github will throw an error, so that single helper method will be able to check if the current api client is authenticated or not. I would add some caching on that call so that you don't deplete your github api ratelimit.

Cool! That's something I've itterated to during last week :+1: 
The cache is invalidated only when credentials are changed, exactly to avoid api retelimit report.

**Comment by acrobat** [comment]
@TomasVotruba I'm going to close this issue as I think it solved. If there is still a problem, feel free to reopen this issue!
