### ISSUE TITLE
Code match

### ISSUE THREAD

**Issue by QuentinRa** [KnpLabs/php-github-api#1024]
Hi, thanks for your wrapper of GitHub API! We can search code using

```php
$files = $client->api('search')->code('@todo language:php');
```

But, could you add a function to get the matched code, as explained [in the official documentation](https://docs.github.com/en/rest/reference/search#text-match-metadata)? This would be a copy of `code`. It may be better to add another argument (rather than creating a new function, up to you), but this code is working for me (inside Search.php)

```php
public function code_match($q, $sort = 'updated', $order = 'desc')
{
    $this->acceptHeaderValue = 'application/vnd.github.v3.text-match+json';
    return $this->get('/search/code', ['q' => $q, 'sort' => $sort, 'order' => $order]);
}
```

**Comment by acrobat** [comment]
Hi @QuentinRa, that would be a feature we can support. Feel free to open a PR to add the functionality!
