### ISSUE TITLE
create blob only 'content' is required

### ISSUE THREAD

**Issue by gemal** [KnpLabs/php-github-api#1042]
https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/GitData/Blobs.php#L62

requires both `content` and `encoding`

but according to the documentation:
https://docs.github.com/en/rest/reference/git#create-a-blob

only content is required

**Comment by acrobat** [comment]
@gemal You are right! Can you send a PR to remove the `encoding` key from the check? Thanks!
