### ISSUE TITLE
psr/cache 3.0.0

### ISSUE THREAD

**Issue by stephenstack** [KnpLabs/php-github-api#1045]
Error below on composer update

- knplabs/github-api v3.3.0 requires psr/cache ^1.0 -> found psr/cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Is there support for psr/cache 3.0.0?

**Comment by acrobat** [comment]
Hi @stephenstack, we only use and not extend from any cache classes/interfaces so we are able to support v3. Can you send a PR to allow v3? Thanks!

See https://github.com/KnpLabs/php-github-api/blob/6b22a81626408772d62774ccc1d3c528c163f3b7/composer.json#L27

**Comment by stephenstack** [comment]
PR Sent, thanks for fast reply

**Comment by acrobat** [comment]
Fixed in #1046
