### ISSUE TITLE
Pagination issue in CurrentUser's repositories API

### ISSUE THREAD

**Issue by SOHELAHMED7** [KnpLabs/php-github-api#1052]
I am trying to fetch repositories of authenticated user's by  `Github\Api\CurrentUser::repositories()` `GET /user/repos` API. [Github docs](https://docs.github.com/en/rest/reference/repos#list-repositories-for-the-authenticated-user)

I took reference from the [docs](https://github.com/KnpLabs/php-github-api/blob/master/doc/result_pager.md) about how to utilise pagination.

The example in the docs (`Github\Api\Organization::repositories()`) have `$page` as method param while `Github\Api\CurrentUser::repositories()` does not have it.

So how to paginate results in `Github\Api\CurrentUser::repositories()` `GET /user/repos` API?

If this is the issue then there are lot APIs which does not have `$page` param support.

**Comment by acrobat** [comment]
Hi @SOHELAHMED7,

If you want to paginate over all results of an api endpoint, you should use the [resultPager](https://github.com/KnpLabs/php-github-api/blob/master/doc/result_pager.md#usage-examples) class. This class takes care of all internal details to actually change the page and so on.

**Comment by SOHELAHMED7** [comment]
I used exactly that 

```php
/** @var \Github\Client $client */
        $client = $this->client;
        $organizationApi = $client->api('me');

        $paginator = new ResultPager($client);

        $repos = $paginator->fetch($organizationApi, 'repositories', [[
            'all',
            'pushed',
            'desc',
            'all',
            'owner,collaborator,organization_member',
            100,
            $page
        ]]);
```

But this has no effect. It always return result of first page.

More info:

Line https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/ResultPager.php#L87 unpacks method params

Line https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/CurrentUser.php#L124 does not have any `page` method param/argument, so pagination does not happen

**Comment by acrobat** [comment]
As the docs state the `fetch` method only gets the next page, if you want all data you should use `fetchAll`. In fact the docs are not fully up to date on the latest changes so you also have a `fetchAllLazy` method that will return an iterator instead.

Example:

```php
$client = new \Github\Client();
$client->authenticate('XXXXX', \Github\Client::AUTH_ACCESS_TOKEN);

$paginator  = new Github\ResultPager($client); // Optional: The second argument takes the items per page
$result = $paginator->fetchAll($client->pullRequest(), 'all', ['KnpLabs', 'php-github-api', ['state' => 'closed']]); // Or use fetchAllLazy to get an iterator instead an result array

// or

$result = $paginator->fetch($client->pullRequest(), 'all', ['KnpLabs', 'php-github-api', ['state' => 'closed']]);
while ($paginator->hasNext()) {
    $result = $paginator->fetchNext();
}
```

**Comment by SOHELAHMED7** [comment]
> As the docs state the fetch method only gets the next page

Agree. That is what I need

In my case I don't need `fetchAll` or `fetchAllLazy`

My use case is: 

I have HTML form

I have select2  drop down

When user change slection to GitHub

Browser send AJAX request to server

I show there first 100 repos. 

If there is next page, and if the users haven't found their repo yet, then I display 'Load more' button

If the Load more button is clicked

Browser send other AJAX request which return repos of second page

---

So for repos of authenticated user, the question still stand how can I fetch repos of say page 3 directly without using `fetchAll` or `fetchAllLazy`

We can achieve this in org/repos API as it has `$page` param in method signature as I mentioned in https://github.com/KnpLabs/php-github-api/issues/1052#issuecomment-1026916523 but not in CurrentUser (`/user/repos`) API

**Comment by hotrush** [comment]
No idea why it was closed, it still not possible to paginate current user repositories properly, method doesn't have page and per_page arguments.

**Comment by NWBY** [comment]
For those who arrive here in the future. Although not obvious this is possible if you don't use the `currentUser()` method and instead pass `currentUser` to the `api()` method.

Here is how I did it, assuming you have already created a client and authenticated a user:
```php
$pager = new ResultPager($client);
$api = $client->api('currentUser');

return $pager->fetchAll($api, 'repositories');
```
