### ISSUE TITLE
Get number of commits between two dates?

### ISSUE THREAD

**Issue by kylescousin** [KnpLabs/php-github-api#1064]
Github API provides this endpoint: https://api.github.com/repos/bitcoin/bitcoin/commits?since=2021-01-06&until=2021-01-07

Does the PHP client support these parameters?

```
public function commits($q, $sort = null, $order = 'desc')
    {
        // This api is in preview mode, so set the correct accept-header
        $this->acceptHeaderValue = 'application/vnd.github.cloak-preview';

        return $this->get('/search/commits', ['q' => $q, 'sort' => $sort, 'order' => $order]);
    }
```

**Comment by kylescousin** [comment]
As the results are paginated, it's hard to tell without doing a get request to every page until the resultset is empty.
Is there a way to get the total count of commits between two dates?

**Comment by acrobat** [comment]
@kylescousin I think you best move to a graphql query to get this data. I'm not sure if this fully fits the usecase but you get the idea and it might help you

```graphql
query {
  repository(owner: "symfony", name: "symfony") {
    object(expression: "4.4") {
      ... on Commit {
        history(since: "2021-06-22T04:37:29Z", until: "2022-06-22T04:37:29Z") {
          totalCount
        }
      }
    }
  }
}
```

Result:

```json
{
  "data": {
    "repository": {
      "object": {
        "history": {
          "totalCount": 1282
        }
      }
    }
  }
}
```
