### ISSUE TITLE
How to call an endpoint that isn't currently supported

### ISSUE THREAD

**Issue by KodeStar** [KnpLabs/php-github-api#1073]
I'm trying to hit https://docs.github.com/en/rest/migrations/source-imports which isn't currently in this library apart from a close PR that never got added.

I'm trying:
```
$client = new \Github\Client();
$client->getHttpClient()->put('/repos/OWNER/REPO/import', [], json_encode([
    'vcs' => 'git',
    'vcs_url' => 'http://github.com/lovingmemory/lovingmemory',
]));
```

But that is returning 'Not Found'.

Is there something I'm doing wrong with that call?

**Comment by GuySartorelli** [comment]
Just as a sanity check, are you putting the actual value for OWNER and REPO in `/repos/OWNER/REPO/import`?

**Comment by KodeStar** [comment]
Lol, I can see why you asked that as I replaced them in the put, but not in the vcs_url, in the example above but yeah I was. the actual line looked like:
```
$client = new \Github\Client();
$client->getHttpClient()->put('/repos/lovingmemory/'.$org.'/import', [], json_encode([
    'vcs' => 'git',
    'vcs_url' => 'http://github.com/lovingmemory/lovingmemory',
]));
```
I ended up not using it anyway (I'm using https://github.com/GrahamCampbell/Laravel-GitHub and using the Facade `Github::getHttpClient()->put` actually worked fine) as it seems there is a bug when importing where workflows don't work on the new repository https://github.community/t/workflows-from-an-imported-repository-not-working/257203 . So I set the original repo as a template and used createFromTemplate instead
