### ISSUE TITLE
Repo documentation out-of-date?

### ISSUE THREAD

**Issue by ultimike** [KnpLabs/php-github-api#1079]
Unless I'm not understanding something correctly, it appears that some of the code samples in doc/repo/contents.md are incorrect.

For example, in the https://github.com/KnpLabs/php-github-api/blob/master/doc/repo/contents.md#get-information-about-a-repository-file-or-directory section, is `->contents()` necessary/correct?

In fact, is `->contents()` necessary in any of the `$client->api('repo')` examples on that page?

I'm happy to submit a pull request to update, but I'm new to this library and wanted to double-check before doing so.

thanks,
-mike

**Comment by acrobat** [comment]
The `->contents()` call is indeed necessary as the related api calls to file content of a repository are located in [Repo/Contents.php](https://github.com/KnpLabs/php-github-api/blob/2fe12b82a7/lib/Github/Api/Repository/Contents.php)

Unless I misunderstand your question, there should be no doc changes. Please leave a comment/re-open the issue if there are still changes required!

**Comment by ultimike** [comment]
Understood. Thanks so much.
