### ISSUE TITLE
Secrets Scanning Alerts

### ISSUE THREAD

**Issue by ls-philippe-gamache** [KnpLabs/php-github-api#1080]
Add Secrets Scanning Alerts for Entreprise, Organizations and Repository

https://docs.github.com/en/enterprise-server@3.5/rest/secret-scanning#list-secret-scanning-alerts-for-an-enterprise
call : Sprintf("enterprises/%v/secret-scanning/alerts", %enterprise)

https://docs.github.com/en/enterprise-server@3.5/rest/secret-scanning#list-secret-scanning-alerts-for-an-organization
call : Sprintf("orgs/%v/secret-scanning/alerts", %org)

https://docs.github.com/en/enterprise-server@3.5/rest/secret-scanning#list-secret-scanning-alerts-for-a-repository
call : Sprintf("repos/%v/%v/secret-scanning/alerts", owner, repo)

**Comment by acrobat** [comment]
Hi @ls-philippe-gamache, thanks for the feature-request. Feel free to open a PR to add these endpoints (together with a few tests and docs)!
