### ISSUE TITLE
Suggestion to remove authorizations::create from doc

### ISSUE THREAD

**Issue by rafasashi** [KnpLabs/php-github-api#1087]
It seems that the following method doesn't exist any longer or am I missing a dependency? 

https://github.com/KnpLabs/php-github-api/blob/3467a347db3027815ca012461e0583c7d0284717/doc/authorizations.md?plain=1#L25

https://github.com/KnpLabs/php-github-api/blob/9c57106b7ba55c17d0a2d9a6e7cef4cd4c637e4d/doc/two_factor_authentication.md?plain=1#L18

**Comment by acrobat** [comment]
These endpoints were indeed deprecated and removed in V3. (https://github.com/KnpLabs/php-github-api/commit/2fe12b82a7fe5896ae4f067d4c62326c4041602f) 

Can you send a PR to cleanup the docs @rafasashi? Thanks!

**Comment by rafasashi** [comment]
Thanks for the feedbak @acrobat ! Here the PR #1090
