### ISSUE TITLE
Http\Client\HttpClient Deprecation

### ISSUE THREAD

**Issue by Fabricio872** [KnpLabs/php-github-api#1119]
The project is using Http\Client\HttpClient which is deprecated since symfony/framework-bundle 6.3 and it is recommended to be replaced with Psr\Http\Client\ClientInterface.

**Comment by mbabker** [comment]
The deprecation in Symfony is that the `Http\Client\HttpClient` service alias will no longer be created in 7.0 (thanks in part to https://github.com/php-http/httplug/pull/171 which deprecates that interface).  To my recollection, there isn't anything in this package that hard requires that interface anymore as everything either uses PSR-17/18 or other HTTPlug objects.

Can you post a stack trace showing how the deprecation is triggered or an example of how your services are configured that would cause this deprecation to be triggered in a Symfony app?

**Comment by acrobat** [comment]
Closing this issue for now as indeed the deprecation itself is not related to this library. If you still have problems reopen this issue or open a new issue. Thanks.
