### ISSUE TITLE
Allow php-http/cache-plugin version 2

### ISSUE THREAD

**Issue by tacman** [KnpLabs/php-github-api#1127]
There's a deprecation warning triggered by this library because it's using 1.x of the php-http/cache-plugin

I think if you simply allowed either ^1.7 || ^2.0 it could use the later version that does not call the deprecated interface.

This _might_ be related to #1119.

Specifically, it's this PR: https://github.com/php-http/cache-plugin/commit/35625293aedba53ca49bb4bd06ac7d12239a89d9

**Comment by acrobat** [comment]
@tacman can you provide the deprecation message you get? Thanks!

**Comment by tacman** [comment]
I'm not getting it anymore, perhaps they back ported the fix.

**Comment by aszenz** [comment]
@tacman I'm still seeing this deprecation, looking at `composer.json` of v1:

https://github.com/php-http/cache-plugin/blob/1.x/composer.json#L17, it still requires the deprecated interface

**Comment by tacman** [comment]
Yep.  I'll reopen.

**Comment by aszenz** [comment]
Version 2 of php-http/cache-plugin is unreleased, only the branch is created

**Comment by ls-philippe-gamache** [comment]
2.0.0 release on 2024-02-19 17:02 UTC
