### ISSUE TITLE
Cannnot Remove an Issue

### ISSUE THREAD

**Issue by iatanasov77** [KnpLabs/php-github-api#1139]
On Git Hub i can Remove issues but i cannot remove with this api or i dont know how i look that in class Github\Api\Issue has not method remove().

**Comment by PedroTroller** [comment]
The library is only a mirror of Github's REST API, and the API cannot be used to remove a problem.
  - https://docs.github.com/fr/rest/issues?apiVersion=2022-11-28

BTW it's not possible to remove an issue for the web interface as well, only to close it.

You can close an issue by updating its `state` to `close`.
 - https://docs.github.com/fr/rest/issues/issues?apiVersion=2022-11-28#update-an-issue

**Comment by iatanasov77** [comment]
I understand. Thanks for your response.
