### ISSUE TITLE
Confusion over authenticate()

### ISSUE THREAD

**Issue by m4tthumphrey** [KnpLabs/php-github-api#15]
Should this not work?

```
$token = '...'; // already authenticated and saved
$client->authenticate($token, null, \Github\Client::AUTH_URL_TOKEN);
```

Whenever I try a request such as 

```
$client->api('me')->show();
```

I get a `Bad Credentials` error. I have tested the token in a simple browser GET request and it returns as expected.... What am I missing?

Edit: After a about an hour on this I noticed a typo in the token. What a joke.

**Comment by onassar** [comment]
@m4tthumphrey what was the solution to this? Going through it now.
