### ISSUE TITLE
Update to Guzzle 5 or 6

### ISSUE THREAD

**Issue by cmfcmf** [KnpLabs/php-github-api#157]
https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#3x-to-40

(most notably, Guzzle 4 does not need cURL anymore).

**Comment by sstok** [comment]
I would even vote for adding support for Guzzle 5.
http://mtdowling.com/blog/2014/10/13/guzzle-5/

**Comment by GrahamCampbell** [comment]
Or Guzzle 6. :P

**Comment by sstok** [comment]
Not released yet :yum: my mean reason for Guzzle 5 is upload progress callback :stuck_out_tongue: (which I like to use in Gush with release assets-uploading). There is a plug-in for Guzzle 4 but its deprecated.

**Comment by GrahamCampbell** [comment]
:+1: For guzzle 5. The upgrade to guzzle 6 shouldn't be that bad from what I see of it so far, but probably more than guzzle 4 -> guzzle 5 was.

**Comment by stof** [comment]
The issue with migrating from Guzzle 3 to Guzzle 4+ is that it is a breaking change, given that they are totally separate projects.

**Comment by Swader** [comment]
+1 for Guzzle 5

**Comment by pilot** [comment]
+1 for 5

**Comment by cmfcmf** [comment]
Guzzle 6 has been released: https://github.com/guzzle/guzzle/releases/tag/6.0.0.

**Comment by GrahamCampbell** [comment]
:+1: guzzle 6

**Comment by xabbuh** [comment]
What about relying on something like [egeloen/http-adapter](https://github.com/egeloen/ivory-http-adapter) to be independent of a concrete HTTP client implementation?

**Comment by pilot** [comment]
@xabbuh interesting...

**Comment by cursedcoder** [comment]
good idea @xabbuh

**Comment by GrahamCampbell** [comment]
I'd prefer just using guzzle 6. We can get more performance with concurrent requests that way.

**Comment by cursedcoder** [comment]
@GrahamCampbell yes, but still this library does not support concurrent requests yet.

**Comment by GrahamCampbell** [comment]
> but still this library does not support concurrent requests yet.

Guzzle does, and the other one never will as far as I can see.

**Comment by cursedcoder** [comment]
@GrahamCampbell I mean `php-github-api` itself is designed for handling single requests.

**Comment by GrahamCampbell** [comment]
> itself is designed for handling single requests.

There's no reason why that can't change during a guzzle 6 upgrade.

**Comment by sroze** [comment]
:+1:

**Comment by byan** [comment]
+1 for guzzle 6. This package is the only one which require guzzle 3.x for me so far. At least it will help me reduce our deployment size if it update to guzzle 6.

**Comment by Soullivaneuh** [comment]
I'm :+1: for Guzzle upgrade but :-1: for v6 minimum requirement.

Developers can require a lower version to them projects and we have to be BC as possible.

I can work on a PR to support Guzzle 4, 5 and 6. This is not very hard, see an sample: https://github.com/nexylan/cloudflare/blob/2d4fe81231a8bb3dab1ecc952fdf3b25edc59602/src/HttpClient/GuzzleHttpClient.php#L64

**Comment by GrahamCampbell** [comment]
:-1: For guzzle 4 as it's EOL just the same as guzzle 3.

**Comment by sstok** [comment]
Instead of depending on Guzzle I would vote for a PSR-7 solution.
Like https://php-http.readthedocs.org/en/latest/httplug/introduction.html

Simple provide a HttpClientInterface httplug implementation. Upgrading is easy and no BC is broken :+1:

**Comment by sroze** [comment]
I like the idea of HttpPlug as it looks like that it will solve all the problems introduced by the different versions of Guzzle.

**Comment by visitek** [comment]
+1 for 5

**Comment by GrahamCampbell** [comment]
> I like the idea of HttpPlug as it looks like that it will solve all the problems introduced by the different versions of Guzzle.

Nah, I tried it. No offence, but it was pretty stupid. Ended up with like 100 more dependencies.

**Comment by jbrooksuk** [comment]
This can be closed, can't it?

**Comment by GrahamCampbell** [comment]
Just read my last comment here. :trollface: :trollface: :trollface: :trollface: :trollface:
