### ISSUE TITLE
Add PHP code sniffer to build

### ISSUE THREAD

**Issue by aztech-dev** [KnpLabs/php-github-api#170]
Since you guys seem to have well defined coding standards, have you considered using [phpcs](https://packagist.org/packages/squizlabs/php_codesniffer) to enforce them (and invalidate builds that dont respect them) ?

**Comment by guillermoandrae** [comment]
As soon as my other PR goes through, I'll clean up my commit and send it in for review.

**Comment by stof** [comment]
Rather than making the Travis build responsible for this, I would rather recommend enabling Scrutinizer and making it responsible for running PHPCS checks. This way, Travis would still be about test failures only.

**Comment by GrahamCampbell** [comment]
I agree. I see a lot of people wanting to misuse travis in this way.

**Comment by guillermoandrae** [comment]
No problem.  Will make the necessary changes.

**Comment by GrahamCampbell** [comment]
This can be closed now as StyleCI is already enabled on this repo and php-cs-fixer config is present.
