### ISSUE TITLE
api_limit is hard coded to 5000

### ISSUE THREAD

**Issue by garak** [KnpLabs/php-github-api#211]
It would be nice getting a dynamic api_limit.
Default value should be 60 (the standard limit without authentication) and should change to 5000 only if authentication is used.

**Comment by sdeering** [comment]
Is there a way to query the current API usage?

**Comment by mAAdhaTTah** [comment]
[It's returned in the headers.](https://developer.github.com/v3/#rate-limiting)

**Comment by sdeering** [comment]
Yes I see that but is there seems to only be a mediator function to access the request header values. 

ie consider the API call and access to the header response:
```
    $response = $this->client->getHttpClient()->get('users/whatever');
    $usage["auth"]["limit"] = (string)$response->getHeader('X-RateLimit-Limit');
    $usage["auth"]["remaining"] = (string)$response->getHeader('X-RateLimit-Remaining');
    $usage["auth"]["usage"] = intval($usage["auth"]["limit"]) - intval($usage["auth"]["remaining"]);
```
Doesn't seem to be accurate and is stuck at 4999.

![image](https://cloud.githubusercontent.com/assets/1787454/7079654/4ea472d8-df6a-11e4-9725-bf734e1fe86b.png)

**Comment by cursedcoder** [comment]
@sdeering you can use guzzle events to process any http data:
```php
use Guzzle\Common\Event;

$client->getHttpClient()->addListener('request.success', function(Event $event) {
    $remaining = $event['response']->getHeader('X-RateLimit-Remaining');

    var_dump($remaining);
});

$client->user()->show('cursedcoder');
```
see list of events http://guzzle3.readthedocs.org/http-client/request.html#plugins-and-events
