### ISSUE TITLE
Fork?

### ISSUE THREAD

**Issue by keradus** [KnpLabs/php-github-api#228]
Hi!
KnpLabs/php-github-api say it's a fork of ornicar/php-github-api, the second one teel it is not maintained anymore and one should go... here.
Maybe convert this repo to standalone one, not forked one ?

**Comment by stof** [comment]
The only way to change the root repo of a github network is to ask the Github support to do it AFAIK

**Comment by keradus** [comment]
any news?

**Comment by cursedcoder** [comment]
done

**Comment by keradus** [comment]
That's great!
