### ISSUE TITLE
Authorizations.php

### ISSUE THREAD

**Issue by apramana** [KnpLabs/php-github-api#236]
According to the [Github docs](https://developer.github.com/v3/oauth_authorizations/), this is the call to check authorizations:
> GET /applications/:client_id/tokens/:access_token

In the Authorizations.php file, this is what's being used:
> GET /authorizations/:client_id/tokens/:access_token

I had to make this change to get token checking to work, so I'm assuming this isn't an alias.

**Comment by cursedcoder** [comment]
fixed in #277
