### ISSUE TITLE
Missing deployments api

### ISSUE THREAD

**Issue by Nebo15-Marvin** [KnpLabs/php-github-api#237]
https://developer.github.com/v3/repos/deployments/

**Comment by GrahamCampbell** [comment]
Please review existing pull requests for creating duplicates. Please close this.

See https://github.com/KnpLabs/php-github-api/pull/174..

**Comment by Nek-** [comment]
Actually it could be good adding tests a fix the current PR.

**Comment by AndrewDryga** [comment]
@GrahamCampbell I don't have right to close PRs.
