### ISSUE TITLE
Cannot bring back more than 100 results

### ISSUE THREAD

**Issue by jbrooksuk** [KnpLabs/php-github-api#243]
I'm using `$paginator->fetchAll($me, 'repositories')` and yet I can only get 100 results back - is something broken in the paginator or am I missing something?

**Comment by GrahamCampbell** [comment]
Yeh, I'm stumped too.

**Comment by GrahamCampbell** [comment]
This is resolved now thanks to @stof. This can be closed now.

**Comment by stof** [comment]
For reference, see https://github.com/StyleCI/StyleCI/issues/154#issuecomment-75113420 for the resolution
