### ISSUE TITLE
How to add a member to a team

### ISSUE THREAD

**Issue by nWidart** [KnpLabs/php-github-api#246]
Hello,

I would like to add members to a origination's team.
Since this isn't documented, how should I do this?

I've tried:

``` php
return $this->client->organization()->teams()->addMember('platform-beta', $githubUsername);
```
returns 'Not Found'

Also trying to show team info with `$this->client->organizations()->teams()->show('Platform Beta')` results in 'Not Found'

I can show the organization info though, using `$this->client->organizations()->show('AsgardCms')`

Thank you,

**Comment by nWidart** [comment]
Ok found how :

Had first to get all the teams:

``` php
$this->client->organization()->teams()->all('AsgardCms')
```

Then using the **team id**
in the `->addMember()` method.

**Comment by hyunhonghyub** [comment]
can i see your source code?

i want detail info,,
