### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by sdeering** [KnpLabs/php-github-api#251]
Hi guys,
If I make a request for a user/repo which doesn't exist I get this error. I'm using Laravel 5.0 any ideas how to catch this?
Thanks

![image](https://cloud.githubusercontent.com/assets/1787454/6552522/5f74180c-c692-11e4-8cc5-fabcb6066df7.png)

**Comment by jrean** [comment]
https://github.com/KnpLabs/php-github-api/tree/master/lib/Github/Exception

`try / catch`

**Comment by sdeering** [comment]
Thanks mate, yeah I'll try that was having issues with catching the exceptions with the Laravel package which uses this KNP one. We can close this, and re-open if needed.
