### ISSUE TITLE
Handle redirected repositories

### ISSUE THREAD

**Issue by garak** [KnpLabs/php-github-api#252]
We know that Github is a bit unfair about "moved" repositories (e.g. a repositories that was under a username and now is under a different one): it replies with a 301 via http, but it replies with a 404 via API.
I'm wondering if we could resolve the problem in this library.
Some possible solutions are listed in [this issue](https://github.com/codetriage/codetriage/issues/240)

**Comment by cursedcoder** [comment]
@garak as I see there's no possibility to implement it in current lib.

But users can retrieve repositories by id across `moved` issue.

**Comment by garak** [comment]
How am I supposed to know the id of a repository? :sad:

**Comment by cursedcoder** [comment]
@garak it's returned with a `repo` apis.

**Comment by garak** [comment]
Trying to be more explicit: Is there a way to get the id of a repository from repository name? Possibly, the name is not the current one, but the "legacy" one (in case of moved repository)

**Comment by stof** [comment]
The preview version of the API now redirects for moved repositories too: https://developer.github.com/changes/2015-04-17-preview-repository-redirects/

**Comment by garak** [comment]
Thank you @stof 
So, is there any chance to implement such new API version here? Maybe we could reopen this issue?

**Comment by stof** [comment]
@garak just set the header in the guzzle client used by the API client, and it will work automatically

**Comment by cursedcoder** [comment]
@garak you can use:
```php
$client->setOption('api_version', 'quicksilver-preview');
```

**Comment by garak** [comment]
@cursedcoder jsut tried your solution, but the header is ``Accept: application/vnd.github.beta+json``, not the expected ``Accept: application/vnd.github.quicksilver-preview+json``

**Comment by cursedcoder** [comment]
@garak in addition try to call:
```php
$client->clearHeaders();
```
should work.

**Comment by garak** [comment]
Solved by calling 

```
$client->getHttpClient()->setHeaders(['Accept' => 'application/vnd.github.quicksilver-preview+json']);
```

Thank you anyway!
