### ISSUE TITLE
Branches Pagination

### ISSUE THREAD

**Issue by renatokd** [KnpLabs/php-github-api#254]
Hello!

How can I make the paging branches?

I found not the ResultPager documentation.

Thank U

**Comment by GrahamCampbell** [comment]
Same way everything else works.

**Comment by GrahamCampbell** [comment]
I use the paginator in there. Feel free to take a look: https://github.com/StyleCI/StyleCI.

**Comment by GrahamCampbell** [comment]
https://github.com/StyleCI/StyleCI/blob/master/app/GitHub/Branches.php

**Comment by pilot** [comment]
@GrahamCampbell :+1:

**Comment by pierrejoye** [comment]
Well, let answer the question using this library and not some other random one (nice one btw @GrahamCampbell !):

$client = new \Github\Client();
$client->authenticate($token, null, $urltoken);
$pager = new \Github\ResultPager($client);
$api = $client->api('repo');
$method ='branches';
$params = ['php', 'php-src'];
$branches = $pager->fetchAll($api, $method, $params);
