### ISSUE TITLE
Get only Latest non-pre-release release?

### ISSUE THREAD

**Issue by dovy** [KnpLabs/php-github-api#269]
I'd love an option to EASILY get the latest, non-pre-release release.  ;)

**Comment by GrahamCampbell** [comment]
I'd argue array_filter is pretty easy.

**Comment by dovy** [comment]
Yes, but there's a new github API call for it. ;)

**Comment by cursedcoder** [comment]
which call @dovy ?

**Comment by dovy** [comment]
I just manually used your run, but here it is:
https://developer.github.com/changes/2015-02-18-new-releases-api-methods/

Only does actual releases, not pre-release.  ;)

**Comment by dovy** [comment]
:+1:
