### ISSUE TITLE
Get all closed pull request

### ISSUE THREAD

**Issue by ahusar** [KnpLabs/php-github-api#270]
Based on the documentation, we have to use `$client->api('pull_request')->all($owner, $projectName,'closed' )` line of code in order to get all closed pull requests. 

If we use this, we get the next error: 

```php
Argument 3 passed to Github\Api\PullRequest::all() must be of the type array, string given
```

If I put the last parameter as array, I am getting only the opened pull requests.

Is there a way to get all the merged pull requests? Or at least all the closed pull requests?

**Comment by stof** [comment]
The documentation is outdated
