### ISSUE TITLE
Github Api V3 report

### ISSUE THREAD

**Issue by jrean** [KnpLabs/php-github-api#273]
Hi,

In case someone is scratching his head as I did. I discovered the cache system won't work if you try to hit a **private** repository. I started debugging and discovered the issue is coming from Github. **I contacted them and opened a ticket which is in progress.**

The `etag` returned is never the same...

**So if anyone encounter the same issue, just be patient it should be fixed soon by Github.**

--

* 1 
```
curl -i -H "Authorization: token :token" \
https://api.github.com/repos/:user/:repo/contents
```
**Returns 200**

* 2
```
curl -i -H "Authorization: token :token" \
-H "If-Modified-Since: :date" \
https://api.github.com/repos/:user/:repo/contents
```
**Returns 304 GREAT**

* 3
```
curl -i -H "Authorization: token :token" \
-H 'IF-None-Match: ":etag"' \
https://api.github.com/repos/:user/:repo/contents
```
**Should returns 304 BUT returns 200**

* 4
```
curl -i -H "Authorization: token :token" \
-H 'IF-None-Match: ":etag"' \
-H "If-Modified-Since: :date" \
https://api.github.com/repos/:user/:repo/contents
```
**Should returns 304 BUT returns 200**

**Comment by stof** [comment]
This shoould be reported to Github. This repo is the PHP API client. It consumes the API, and is not maintained by the github team. So it cannot do anything about misbehaviors of the API itself.

**Comment by jrean** [comment]
@stof LOOOOOOOOL

Why don't you never read POSTS!!!

> In case someone is scratching his head as I did. I discovered the cache system won't work if you try to hit a private repository. I started debugging and discovered the issue is coming from Github. **I contacted them and opened a ticket which is in progress.**

**Comment by stof** [comment]
@jrean but posting this ticket here makes no sense at all, as it is purely as server-side issue with the API

**Comment by jrean** [comment]
Thank for judging if something is useful or not. I'm just sharing something with the community to save eventually someone time (I lost myself). You're so negative...

**Comment by cursedcoder** [comment]
Thank you @jrean 
That's helpful
