### ISSUE TITLE
Get a Reference error

### ISSUE THREAD

**Issue by liaohuqiu** [KnpLabs/php-github-api#281]
From: https://developer.github.com/v3/git/refs/#get-a-reference

> `GET /repos/:owner/:repo/git/refs/:ref`

> The `ref` in the URL must be formatted as `heads/branch`, not just branch. For example, the call to get the data for a branch named `skunkworkz/featureA` would be:
>  `GET /repos/:owner/:repo/git/refs/heads/skunkworkz/featureA`

If we want to get the information of `master`, should be

```
GET /repos/:owner/:repo/git/refs/heads/master
```

But, I saw in the code in `References.php`

```
public function show($username, $repository, $reference)
{
    return $this->get('repos/'.rawurlencode($username).'/'.rawurlencode($repository).'/git/refs/'.rawurlencode($reference));
}
```

The `$reference`: `heads/master` after `rawurlencode` will be:

```
GET /repos/:owner/:repo/git/refs/heads%2Fmaster
```

**Comment by cursedcoder** [comment]
should be fixed with:
```php
$reference = implode('/', array_map('rawurlencode', explode('/', $reference)));
```

**Comment by liaohuqiu** [comment]
There are still some other same issues in the `References.php`

**Comment by cursedcoder** [comment]
closed https://github.com/KnpLabs/php-github-api/commit/ccf5e49a2454c1b102333586d80ce67012b5080f
