### ISSUE TITLE
Adding a team to a repo missing permissions

### ISSUE THREAD

**Issue by timbeks** [KnpLabs/php-github-api#292]
Hi,

I'm trying to add a team to a repository with the pull/push/admin rights, but the original addTeam with an array of strings for the repo's is deprecated. According to the documentation (https://developer.github.com/v3/orgs/teams/#add-team-repo) you should use teams->addRepository. But at this time, you can't supply the argument anywhere.

Also, in the methods of team, it uses for repository()/addRepository()/removeRepository() the var $username, but this should be $organization.

**Comment by acrobat** [comment]
@cursedcoder issue can be closed. The missing parameter was added in #388 and I've created a PR (#483) for the incorrect parameter name.
