### ISSUE TITLE
Can't return all comments in a repo

### ISSUE THREAD

**Issue by floored1585** [KnpLabs/php-github-api#293]
Hey there, I'm trying to get all comments in a repo.  You can do this via the API as follows:

https://api.github.com/repos/floored1585/SmartCart/issues/comments

But there is no way to do this (that I can see) in this library.  It would be awesome to have this functionality.

**Comment by GrahamCampbell** [comment]
Yes there is... https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/Issue/Comments.php#L36

**Comment by floored1585** [comment]
Explain?  That requires $issue to be set.  How do you get all comments for a repo, for all issues, as the URL I posted does?

**Comment by floored1585** [comment]
That function returns all comments for an _issue_ not for the entire repo.

**Comment by GrahamCampbell** [comment]
https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/Repository/Comments.php#L36

**Comment by floored1585** [comment]
Ahhh! I will try that, thank you!

**Comment by floored1585** [comment]
Hmm, that looks like it only shows commit comments, not comments on issues.

**Comment by cursedcoder** [comment]
did you try https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/PullRequest/Comments.php#L14 ?

**Comment by floored1585** [comment]
Looks like that's all comments for a pull request.

I ended up hacking around this with the following code, which does what I want but isn't what the code intends.

$comments = $client->api('issue')->show($owner, $repo, 'comments');
