### ISSUE TITLE
Listing all public repositories

### ISSUE THREAD

**Issue by byybora** [KnpLabs/php-github-api#294]
https://developer.github.com/v3/repos/#list-all-public-repositories

I couldnt find how to get all public repositories?

**Comment by cursedcoder** [comment]
seems it's missing @byybora

**Comment by cursedcoder** [comment]
still you can try https://github.com/KnpLabs/php-github-api/blob/master/doc/request_any_route.md

**Comment by byybora** [comment]
@cursedcoder +1 Thanks
