### ISSUE TITLE
Return all users using "all()" API method

### ISSUE THREAD

**Issue by andreybleme** [KnpLabs/php-github-api#295]
Hi guys, 

How does the return limit of the "all()" method works? I'm trying to retrieve most users as possible to get them by some custom filters, but it only return 99 users. I didn't find any explanation about this issue in the docs.

BTW, thanks for the nice API PHP library ;)

**Comment by cursedcoder** [comment]
Use pagination https://github.com/KnpLabs/php-github-api/blob/master/doc/result_pager.md

**Comment by andreybleme** [comment]
Thanks!
