### ISSUE TITLE
Unable to set perPage for Issue::find()

### ISSUE THREAD

**Issue by emersonthis** [KnpLabs/php-github-api#296]
I'm searching for issues as follows:

```
$issues = $paginator->fetchAll($this->client->api('issue'), 'find', array($myorg, $myrepo, $state, $term));
```

In other contexts the `$paginator->fetchAll()` seems to return an unlimited number of results. But here I get a max of 10 no matter which parameters I pass. What am I doing wrong?

**Comment by acrobat** [comment]
Most likely this is already resolved, but for future reference.

FetchAll does actually fetch all records (it loops internally until github doesn't return any results)

If you want to fetch them page by page, you need to call the `ResultPager::fetch` method and afterwards (in a loop) the `ResultPager::fetchNext`.

See the [result pager docs](https://github.com/KnpLabs/php-github-api/blob/master/doc/result_pager.md#get-the-first-page) for more info.
