### ISSUE TITLE
Update Issue::find() to use the new gitHub search

### ISSUE THREAD

**Issue by emersonthis** [KnpLabs/php-github-api#297]
The legacy search doesn't allow filtering by labels or the advanced search syntax on the HTML site. The new search does.

I'd be happy to make a PR for this if you give me some input on how you'd it implemented. Perhaps as a new method along with the existing for backwards compatibility?

**Comment by acrobat** [comment]
@cursedcoder I think this issue can be closed as the search api already uses the new search. See https://github.com/KnpLabs/php-github-api/pull/300#issuecomment-127915453
