### ISSUE TITLE
CachedHttpClient does not differentiate between HTTP verbs when setting cache ID.

### ISSUE THREAD

**Issue by BjornTwachtmann** [KnpLabs/php-github-api#299]
I'm having some trouble doing the following:

``` php
 $exists = $this->client->api('repo')->contents()->exists(
     $this->config['user'],
     $this->config['repository'],
     $this->config['languages_path'],
     $this->config['branch']
 );
 if (!$exists) {
     return false;
 }
 $dirInfo = $this->client->api('repo')->contents()->show(
     $this->config['user'],
     $this->config['repository'],
     $this->config['languages_path'],
     $this->config['branch']
 );
 .....
```

 $dirInfo is always null when using the CachedHttpClient. Reading through the code, this is because exists() makes a HEAD request to the same URL that show() makes a GET request to, and the client is caching a response with an empty body. 

 The simplest solution to this would appear to be to change [https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/HttpClient/CachedHttpClient.php#L85](https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/HttpClient/CachedHttpClient.php#L85) to something like

``` php
 $this->id = $httpMethod . '__' . $path;
```

 The call to exists is probably redundant here anyway, but this seems like a bug that should be fixed. Let me know if you need any more info.

**Comment by docteurklein** [comment]
That's definitly a problem yes. It would be awesome if you could provide a patch :)

Otherwise I think the latest version  of the underlying guzzle provides caching out of the box. It would be even better to rely on it!

**Comment by docteurklein** [comment]
FYI: http://guzzle3.readthedocs.org/plugins/cache-plugin.html does what we tried to do.

**Comment by acrobat** [comment]
In version 2 we use httplug which has a built-in cache plugin which should work as described in the docs. So I'm closing this issue for now, please reopen or leave a comment if you still have issues with the V2 of this library!
