### ISSUE TITLE
Better pagination

### ISSUE THREAD

**Issue by GrahamCampbell** [KnpLabs/php-github-api#301]
It would be good if we could have an iterator that loads pages singularly in memory, instead of loading everything and lumping it into a massive array.

This is something I'd be happy to look into implementing if it's wanted.

**Comment by stof** [comment]
it should be possible to implement it on top of the existing features of the ResultPager btw, as it supports fetching pages one by one

**Comment by GrahamCampbell** [comment]
Yeh. :)

**Comment by GrahamCampbell** [comment]
What I want is a iterator that will seamless fetch pages under the hood so i can iterate the entire data set.

**Comment by emersonthis** [comment]
Yea. I struggled with this too. The current paginator makes it easy to create "next" and "previous" links but there doesn't appear to be a way to show all the intermediate page links. Or even know how many total results there are. Both of those would be really useful for me.

**Comment by GrahamCampbell** [comment]
What?

**Comment by GrahamCampbell** [comment]
I don't think you understand what I want to do.

**Comment by stof** [comment]
@emersonthis it gives you the links to the first, previous, next and last pages, which are the only ones exposed by the Github pagination.

**Comment by GrahamCampbell** [comment]
I'm not interested in how many pages there are at all. I want an iterator that can go to the next entry, regardless of whether it was on the same page, or we had to load a new page.

**Comment by emersonthis** [comment]
@GrahamCampbell I get what you're asking for. I didn't mean to hijack your issue. I just thought the functionality I was describing was related enough to be worth mentioning. But according to @stof it sounds like it's not really realistic anyway, given what's offered via the Github API.

**Comment by GrahamCampbell** [comment]
We only need the next page, so this would be totally realistic, infact, easy.

**Comment by GrahamCampbell** [comment]
Leave this with me, and I'll do something soon.
