### ISSUE TITLE
plz help me to creat authorizations And writing a new repo

### ISSUE THREAD

**Issue by ghost** [KnpLabs/php-github-api#308]
1-Can you give a simple example of how to creat authorizations call back url im use the's code:

``` php
require_once 'vendor/autoload.php';
$client = new \Github\Client();
$data = array(
    'scopes'        => array('user','repo'),
    'client_id'     => $client_id,
    'client_secret'     => $client_secret
);
$a = $client->api('authorizations')->create($data);
echo json_encode($a, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
```

not worck ???
2-And how method of writing a new repo useng authorizations

I am sorry for the English language because I use Google translator
Please help me I am in dire need for this code

**Comment by Tjoosten** [comment]
error stack?

**Comment by acrobat** [comment]
@cursedcoder I think this issue can be closed as the issue creator user is deleted
