### ISSUE TITLE
Are there a demo site?

### ISSUE THREAD

**Issue by ppKrauss** [KnpLabs/php-github-api#309]
For illustration and to ease understand... Are there a demo site?

**Comment by GrahamCampbell** [comment]
How would that make it easier?

**Comment by ppKrauss** [comment]
Only a URL to see and try to use a little bit

**Comment by GrahamCampbell** [comment]
What's wrong with github's docs? They're very detailed.

**Comment by stof** [comment]
And this package does not provide anything viewable on an URL. It is meant to be used in the code of other project. So there is nothing to see on URLs.
