### ISSUE TITLE
Suppoort for webhook ?

### ISSUE THREAD

**Issue by Grummfy** [KnpLabs/php-github-api#310]
Hello,
do you have plan to support webhook ? Not only as client to read webhook setted, but to receive event, interpret the payload, etc.

thanks

**Comment by GrahamCampbell** [comment]
I don't think anything needs to change?

**Comment by Grummfy** [comment]
well, some class to help interpret payload, check header, etc can help

**Comment by GrahamCampbell** [comment]
You mean check the hash?

**Comment by GrahamCampbell** [comment]
Feel free to look at how I deal with security in https://github.com/StyleCI/StyleCI/blob/master/app/Http/Controllers/GitHubController.php#L46.

**Comment by Grummfy** [comment]
Thanks.
But this can be added here like a class to deal with payload. Don't you find it can be usefull for everyone?

**Comment by GrahamCampbell** [comment]
Not really. My code there is quite specific to the framework, and the contaxt.

**Comment by stof** [comment]
@Grummfy given that the API client does not wrap returned types in PHP classes for API methods (which would be a pain to maintain as any new field added by github would be unusable until the client is updated to support them), there is no reason to wrap the webhook payload in a class either.
