### ISSUE TITLE
Rate Limit Endpoint

### ISSUE THREAD

**Issue by quickliketurtle** [KnpLabs/php-github-api#313]
Hello - 
I needed to hit the rate_limit endpoint to verify auth was working and returning the 5000 requests/hr limit instead of the 60 when not authenticated. I added a rate_limit class to your package with some helpers like getCoreLimit() and getSearchLimit(), so i can do say:
    
    $limit = $github->api('rate_limit')->getCoreLimit();

If it would beneficial to others i can submit a PR. But I wanted to checkin to see if there was interest first. 

Thanks.

**Comment by stof** [comment]
Well, supporting all API endpoints is the goal. So if you have an implementation of a missing endpoint, sending a PR makes sense.

**Comment by quickliketurtle** [comment]
This was resolved by PR#314
