### ISSUE TITLE
Support application/octet-stream for binary asset streaming

### ISSUE THREAD

**Issue by jackmcdade** [KnpLabs/php-github-api#320]
Is there any way to support `Content-Type: application/octet-stream` on API requests? Github will pass thru the file stream if you do this.

https://developer.github.com/changes/2013-09-25-releases-api/
https://developer.github.com/v3/repos/releases/#response-8

**Comment by acrollet** [comment]
Looked into doing a PR for this but the interactions between this library and guzzle would take a lot of effort to make it work. Documenting an 'easy enough' approach here. To retrieve an asset, you can get its ID with a call to the releases method and call the following URL:

https://api.github.com/repos/REPOSITORY_NAME/USERNAME/releases/assets/ASSET_ID?access_token=ACCESS_TOKEN

It will return a 302 with a S3 URL, simply retrieve the file from that URL.

**Comment by skwashd** [comment]
@acrollet this is untested, but what about something like this:

```php
public function download($username, $repository, $id)
{
    $headers = [
        'Accept' => 'application/octet-stream',
    ];
    return $this->get('repos/'.rawurlencode($username).'/'.rawurlencode($repository).'/releases/assets/'.rawurlencode($id), [], $headers);
}
```

The guzzle docs say it will follow up to 5 302 redirect by default, so it **should** grab the asset file.

**Comment by acrollet** [comment]
@skwashd I spent quite a bit of time on this ;) The redirects get followed, the issue is that S3 (where the files are stored) does't like seeing the auth token in the header. I experimented with using the url_token authentication method (deprecated) but S3 chokes on that as well. It went beyond the amount of time I could justify spending.

**Comment by GrahamCampbell** [comment]
👍
