### ISSUE TITLE
User events

### ISSUE THREAD

**Issue by RyanHipkiss** [KnpLabs/php-github-api#328]
Hi, 

Do you have any user event methods? I am looking to get :

https://developer.github.com/v3/activity/events/#list-events-performed-by-a-user

but there doesnt seem to be any for this in here as of yet.

**Comment by chrisvogt** [comment]
I came here with a similar question. Check out [Request any Route](https://github.com/KnpLabs/php-github-api/blob/master/doc/request_any_route.md) in the documentation. The following example works for me:

```php
<?php
// This file is generated by Composer
require_once 'vendor/autoload.php';

$client = new \Github\Client(
    new \Github\HttpClient\CachedHttpClient(array('cache_dir' => '/tmp/github-api-cache'))
);
$response = $client->getHttpClient()->get('users/chrisvogt/events/public');
$events     = Github\HttpClient\Message\ResponseMediator::getContent($response);

echo json_encode($events);
```

**Comment by Einenlum** [comment]
It is implented here : https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/User.php#L205
