### ISSUE TITLE
api('repo')->contents()->show() not works with images

### ISSUE THREAD

**Issue by artygrand** [KnpLabs/php-github-api#337]
$fileInfo = $client->api('repo')->contents()->show($vendoe, $repo, $path_to_image);
returns null if file is image

**Comment by morozov** [comment]
Could you please provide the example of `($vendor, $repo, $path_to_image)`? It works for me:
```php
$info = $client->api('repo')->contents()->show('symfony', 'symfony-docs', '_images/release-process.jpg');
var_dump($info);
```
Outputs:
```
array(12) {
  'name' =>
  string(19) "release-process.jpg"
  'path' =>
  string(27) "_images/release-process.jpg"
  'sha' =>
  string(40) "9868404b07f3c96ce316122f012b52ca176769ee"
  'size' =>
  int(315886)
  'url' =>
  string(97) "https://api.github.com/repos/symfony/symfony-docs/contents/_images/release-process.jpg?ref=master"
  'html_url' =>
  string(79) "https://github.com/symfony/symfony-docs/blob/master/_images/release-process.jpg"
  'git_url' =>
  string(100) "https://api.github.com/repos/symfony/symfony-docs/git/blobs/9868404b07f3c96ce316122f012b52ca176769ee"
  'download_url' =>
  string(89) "https://raw.githubusercontent.com/symfony/symfony-docs/master/_images/release-process.jpg"
  'type' =>
  string(4) "file"
  'content' =>
  string(428204) "/9j/4AAQSkZJRgABAQAASABIAAD/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQE..."
  'encoding' =>
  string(6) "base64"
  '_links' =>
  array(3) {
    'self' =>
    string(97) "https://api.github.com/repos/symfony/symfony-docs/contents/_images/release-process.jpg?ref=master"
    'git' =>
    string(100) "https://api.github.com/repos/symfony/symfony-docs/git/blobs/9868404b07f3c96ce316122f012b52ca176769ee"
    'html' =>
    string(79) "https://github.com/symfony/symfony-docs/blob/master/_images/release-process.jpg"
  }
}
```

**Comment by artygrand** [comment]
@morozov Уже не помню, что там было почти год назад
Но, судя по коду, я не смог скачать картинки из этой папки https://github.com/artygrand/test/tree/master/assets

    //$file = GitHub::repo()->contents()
    //    ->download($vendor, $repo, 'assets/screenshot-' . $i . '.jpg');
    $response = $client->getHttpClient()
        ->get('repos/' . rawurlencode($vendor) . '/' . rawurlencode($repo) . '/contents/assets/screenshot-' . $i . '.jpg');
    $file = \Github\HttpClient\Message\ResponseMediator::getContent($response);

тут я использую download, а он наверно show

**Comment by Nyholm** [comment]
Please have the discussion in English so others can follow as well. =)

**Comment by artygrand** [comment]
@Nyholm, lol, look to date of issue. no need to discuss it.
