### ISSUE TITLE
No pagination for repo->branches (and many others)

### ISSUE THREAD

**Issue by mike503** [KnpLabs/php-github-api#340]
Maybe I missed that get() inherits parameters from other means, but I couldn't figure it out.

Making this manual change made sure I didn't get the default limit of 30 it looks like.

``` php
    public function branches($username, $repository, $branch = null)
    {
        $url = 'repos/'.rawurlencode($username).'/'.rawurlencode($repository).'/branches';
        if (null !== $branch) {
            $url .= '/'.rawurlencode($branch);
        }

        return $this->get($url);
    }
```

Hardcoding the parameter for kicks works:

``` php
        return $this->get($url, array('per_page' => 100));
```

Is there a better way I can feed these parameters in the caller? The third parameter is a specific branch name, and I don't see how to add params properly. Couldn't find examples and I suck at OOP. :)

``` php
$branches = $github_client->api('repo')->branches($github_username, $github_repository);
```

IF this is an issue and not just me not understanding the highly chained nature of the OO, then lots of calls are missing the options for parameters.

**Comment by ramsey** [comment]
@mike503, using the [result pager documentation](https://github.com/KnpLabs/php-github-api/blob/master/doc/result_pager.md), I was able to figure out how to do this.

For branches, it looks something like this:

``` php
$repoApi = $client->api('repo');
$paginator = new \Github\ResultPager($client);
$branches = $paginator->fetchAll($repoApi, 'branches', [$owner, $repository]);

foreach ($branches as $branch) {
    // Now, you can loop over all your branches
}
```
