### ISSUE TITLE
[Notification] mark read

### ISSUE THREAD

**Issue by Dgame** [KnpLabs/php-github-api#342]
I got the following error all the time if I try `$this->_client->api('notifications')->markRead();` :

> Problems parsing JSON

**Comment by Einenlum** [comment]
Seems this bug was not reported by anyone else. Closing this issue, but feel free to reopen it if the bug is still there.

**Comment by Einenlum** [comment]
Cf. here: https://github.com/KnpLabs/php-github-api/issues/493
