### ISSUE TITLE
Add membership in organization

### ISSUE THREAD

**Issue by Hadrien45** [KnpLabs/php-github-api#343]
Hello,

According to the Github API (https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership), I try to find the method to "add or update membership in organization".
Is that method was wrapped ?
 
Thanks.

**Comment by corbosman** [comment]
+1.  As of Github Enterprise 2.4.2 these api methods have been fixed to allow org admins to modify org memberships without invites. 

PUT /orgs/:org/memberships/:username

**Comment by xabbuh** [comment]
see #353

**Comment by xabbuh** [comment]
@cursedcoder Can be close now that #353 is merged I think.
