### ISSUE TITLE
"202 Accepted" on getting repository activity

### ISSUE THREAD

**Issue by ostretsov** [KnpLabs/php-github-api#349]
When I try to get repository activity with the following code:
```php
$client->api('repo')->activity($username, $repository);
```
it may return 202 (Accepted) status code as [described in official documentation](https://developer.github.com/v3/repos/statistics/#a-word-about-caching). Should that library manage with that problem (let's say with additional third argument to delay between requests until 200 status code) or it's client-side problem?

Can PR if needed.

**Comment by GrahamCampbell** [comment]
I don't think this is a bug in the library.

**Comment by GrahamCampbell** [comment]
I think it's up to the library consumer to retry later once github have calculated the activity.
