### ISSUE TITLE
Configuring the http client - adding proxy support

### ISSUE THREAD

**Issue by moabi** [KnpLabs/php-github-api#351]
(hope I did not miss this feature...)
Would it be possible to add support for proxy settings as we can already do with

```
$client->getHttpClient()->setOption('user_agent', 'My new User Agent');
```

As I understand only options right now are : 
- base_url
-  user_agent
-  timeout
- api_limit
- api_version
- cache_dir

with something like :

```
$client->getHttpClient()->setOption( 'curl' , array(
                           'CURLOPT_PROXY'           => PROXY_HOST,
                           'CURLOPT_PROXYPORT' => PROXY_PORT
                           ) 
);
```

**Comment by stof** [comment]
The options are any option supported by Guzzle AFAIK.

**Comment by moabi** [comment]
ok my bad, so this should be ok therefore : 
  
    $client->getHttpClient()->setOption('proxy', 'tcp://localhost:8125');

**Comment by moabi** [comment]
Best option would be to define something like : 

    return $this->request($path, null, 'GET', $headers, array(
               'query' => $parameters,
               $request_options,
               ));

where $request_options would be an array of possible guzzle options...

**Comment by Nyholm** [comment]
This issue can be closed. We use HTTPlug which allows you to configure the HTTP client yourself.

**Comment by acidaniel** [comment]
I've implemented it in this way and it works:
```
$this->githubClient->getHttpClient()->client->getConfig()->set('curl.options', ['CURLOPT_PROXY' => 'http://host', 'CURLOPT_PROXYPORT' => '912']);

```
