### ISSUE TITLE
Github 404 Not Found throwing runtime exception

### ISSUE THREAD

**Issue by davidcorbin** [KnpLabs/php-github-api#354]
```
$client->organization()->members()->check(ORGANIZATION, USERNAME);
```

throws

```
Fatal error:  Uncaught exception 'Github\Exception\RuntimeException' with message 'Not Found
```

According to https://developer.github.com/v3/orgs/members/#check-membership, 404 status is the correct response if the user is not a member of the organization.

**Comment by newelement** [comment]
Yes is there a way to turn disable the exceptions for 404 resposes?

**Comment by gophry** [comment]
Guzzle parameter http_errors=>false to disable 404,500 client exceptions.
