### ISSUE TITLE
Validation Failed: Field "path" is invalid, for resource "Commit"

### ISSUE THREAD

**Issue by twardnw** [KnpLabs/php-github-api#360]
Following the example in [doc/repo/contents.md](https://github.com/KnpLabs/php-github-api/blob/master/doc/repo/contents.md) , I am receiving the error: 

```
'Github\Exception\ValidationFailedException' with message 'Validation Failed: Field "path" is invalid, for resource "Commit"' in /Users/twardnw/Sites/d8settings.frost.dev/current/webroot/vendor/knplabs/github-api/lib/Github/HttpClient/Listener/ErrorListener.php on line 91
```
My code is
```
$oldFile = $client->api('repo')->contents()->show($owner, $name, $path, $branch);
$fileInfo = $client->api('repo')->contents()->update($owner, $name, $path, $content, $commitMessage, $oldFile['sha'], $branch, $committer);
var_dump($fileInfo);
```

Any help is appreciated!

**Comment by twardnw** [comment]
Also the same error when using the example to create a new file.

**Comment by twardnw** [comment]
Seems this only happens when I am using rendered PHP to execute the tasks. Switching this to a command-line script works just fine.

**Comment by Tjoosten** [comment]
Can u explain a little more i ran into the same issue.

**Comment by pixeline** [comment]
> 

i would assume this is a permission issue: your php CLI is probably a user with more priviledges than your webserver's user.
