### ISSUE TITLE
How To implement logout

### ISSUE THREAD

**Issue by nepsdotin** [KnpLabs/php-github-api#375]
Hi there,

How do I implement logout, that just logout from my webapp and not github.com

**Comment by GrahamCampbell** [comment]
?

**Comment by nepsdotin** [comment]
I would like to know, How do I implement logout or session invalidation from my webapp when using github api. 

Whats happening is 
1. When I clear all the cookies and login, page is redirected to github login page, it asks me to pucnch in the password, once done
2. I am redirected to main page of my web app
3. But when I move to differnt page and come back to my webapp login page, its taking me to directly to my web app logged in dashboard.

currently i logout with destroying my app related session id, and session info

Pls clarify is this the correct flow... 
if not whats the logout implementation, how do i do that.

-Napoleon

**Comment by GrahamCampbell** [comment]
I don't think this is within the scope of the issues for this repo?

**Comment by xXXIMMATTHEWXXx** [comment]
This does not appear to relate to this. If your talking about a login system. Check out this: https://github.com/DeveloperShed/BasicSecureLogin
