### ISSUE TITLE
77: SSL: Can't Load CA Certificate File - yet works in a standalone example file.

### ISSUE THREAD

**Issue by Vivalldi** [KnpLabs/php-github-api#378]
Currently I have 2 separate PHP script. The first script is a standalone PHP file that I invoke using `php filename.php`. This file creates a new github client, authorizes and checks for a list of repos. The second script is part of a plugin in the Grav CMS that when attempting to check repos `$repositories = $github->api('user')->repositories($ghUsername);` fails returning the inability to open the cacert.pem file. Bear in mind that  Grav CMS utilizes streams (and that `plugins://` is a path in Grav)

Full Error:

```
[curl] 77: SSL: can't load CA certificate file plugins://devtools/cli/../vendor/composer/../guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem [url] https://api.github.com/users/vivalldi/repos?type=owner&so  
  rt=full_name&direction=asc                                                                                                                             
```

**Comment by xXXIMMATTHEWXXx** [comment]
cacert.pem MUST be included in php.ini like such `curl.cainfo="path \ to \ cacert.pem"`
