### ISSUE TITLE
Cannot list user's private repos ?

### ISSUE THREAD

**Issue by gaillafr** [KnpLabs/php-github-api#381]
Hi,

I'm not really sure but regarding the code and some tests I did we cannot list user's private repository (with appropriate scopes of course).

We can do something like that:
```php
$client->api('user')->repositories('username', ...);
```

But regarding the official GitHub API doc, the purpose of the `user` (singular) is to make calls on its own account.

It looks like the package does not provide anything to make this kind of call:
`GET https://api.github.com/user/repos`

Let me know if I missed something,
Thanks.

**Comment by stof** [comment]
use ``->api('current_user')`` to access the ``user`` endpoint rather than the ``users`` one.

**Comment by roukmoute** [comment]
Can it close @gaillafr ?

**Comment by gaillafr** [comment]
Great, it works!
Thx.
