### ISSUE TITLE
Getting all branches

### ISSUE THREAD

**Issue by david-easymarkit** [KnpLabs/php-github-api#384]
Can't seem to figure out how to get all branches and by passing the limit per call.

I do not want to use pagination since I am populating the data into a select list.

**Comment by dennisoehme** [comment]
Pagination in branches request ist really important.

**Comment by stof** [comment]
Use the ResultPager if you want to load all pages: https://github.com/KnpLabs/php-github-api/blob/master/doc/result_pager.md

There is simply no way to get all branches in a single call, as the github API is paginated and does not allow to disable pagination (which totally make sense as disabling pagination would hurt their servers for big lists)

**Comment by dennisoehme** [comment]
Thx @stof!

**Comment by GrahamCampbell** [comment]
This can be closed now?

**Comment by david-easymarkit** [comment]
Thanks @stof
