### ISSUE TITLE
Guzzle is deprecated

### ISSUE THREAD

**Issue by visitek** [KnpLabs/php-github-api#385]
"guzzle/guzzle":   "~3.7"

guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)

**Comment by GrahamCampbell** [comment]
Duplicate. :)

**Comment by GrahamCampbell** [comment]
https://github.com/KnpLabs/php-github-api/issues/157
