### ISSUE TITLE
Null paginator finding repo by keyword.

### ISSUE THREAD

**Issue by abdielcs** [KnpLabs/php-github-api#391]
I'm getting a null pagination searching repos by keyword. Maybe I'm missing something?

```
$client = new Github\Client();
$reposApi = $client->api('repo');
$paginator  = new Github\ResultPager($client);
$parameters = array('collection');
$result     = $paginator->fetch($reposApi, 'find', $parameters);

var_dump($paginator->getPagination());
```

**Comment by acrobat** [comment]
I'm cleaning up old issues. The repository find method was deprecated and removed in 3.0, the `Search::repositories` should be used instead. This produces the correct results and pagination
