### ISSUE TITLE
blob file download

### ISSUE THREAD

**Issue by omidmaldar** [KnpLabs/php-github-api#401]
hi, I'm using this repo through @GrahamCampbell 's [ package](https://github.com/GrahamCampbell/Laravel-GitHub) for Laravel. I get error 

> This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size 

I tried git, gitData and git-data with that but couldn't make it work. do you have any suggestion how can I use it for showing/downloading files bigger than 1MB in Laravel.  
I tried something like this: 
`$fileContent = GitHub::repo('git-data')->contents()->download($this->owner, $this->repo, $path, $ref);`

**Comment by acrobat** [comment]
I'm closing stale issues, if this is still a problem please open a new issue.
