### ISSUE TITLE
Get the Archive stream

### ISSUE THREAD

**Issue by EnzChe** [KnpLabs/php-github-api#402]
Hello,

`$client = new Client();`
`$client->authenticate(Yii::$app->params['git_api_token'], Yii::$app->params['git_api_key'], Client::AUTH_HTTP_TOKEN);`
`$stream = $client->api('repo')->contents()->archive($projectOwner, $projectName, 'zipball');`
`$fileContent = $client->api('repo')->contents()->download($projectOwner, $projectName, 'installSMDE.bat');`
`var_dump($stream); exit;`

The contents()->download works on my private GitHub Repo, but the contents()->archive return an empty string.
Before the last merge (2.0) it was working, am I doing something wrong ?

Thanks.

**Comment by cursedcoder** [comment]
Probably it was broken /cc @Nyholm

**Comment by Nyholm** [comment]
The response is not empty. It is a 302 response. 

I'll send a PR in a moment.

**Comment by Nyholm** [comment]
There, @EnzChe try out the fix in #403. 

Also, @cursedcoder, thank you for the ping.

**Comment by EnzChe** [comment]
Thanks, #403 is working and solving this issue.
