### ISSUE TITLE
Setting the api_version broken on master

### ISSUE THREAD

**Issue by GrahamCampbell** [KnpLabs/php-github-api#411]

**Comment by Nyholm** [comment]
Are you also using setEnterpriseUrl?

What API are you using?

**Comment by GrahamCampbell** [comment]
The code is essentially this:

```
$client = new Client();

$client->addCache(new CacheItemPool(/* some psr cache implementation */));

$client->setOption('api_version', 'custom-version-goes-here');

// then just authentication, and that's it
```

**Comment by GrahamCampbell** [comment]
All this stuff was working before the psr6 stuff came in.

**Comment by GrahamCampbell** [comment]
Basically, it's https://github.com/GrahamCampbell/Laravel-GitHub/tree/master/src.

**Comment by GrahamCampbell** [comment]
Calling `$client->clearHeaders();` after fixed it.

**Comment by Nyholm** [comment]
Interesting. I'll try to debug this tonight.

**Comment by GrahamCampbell** [comment]
I guess it's pretty clear why it's happening, right. The setOptions method doesn't mark the headers as old?

**Comment by Nyholm** [comment]
Fact is, the Accept header was not set at all until you call `clearHeaders`. Please try the patch in PR #415 to see if it works.
