### ISSUE TITLE
Get commit signature

### ISSUE THREAD

**Issue by Geolim4** [KnpLabs/php-github-api#412]
Hi,

Is it a bug that the commit signature is not provided, or did you just follow the [Commit Signature Verification notice](https://developer.github.com/v3/repos/commits/#commit-signature-verification) ?

Cheers,
Georges.L

**Comment by cursedcoder** [comment]
For that you need to set your `Accept` header to `application/vnd.github.cryptographer-preview` as per documentation.

In this library by default version is set to `v3`, see https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Client.php#L368

```
$client->setOption('api_version', 'cryptographer-preview');
```
