### ISSUE TITLE
Exception handling still broken

### ISSUE THREAD

**Issue by GrahamCampbell** [KnpLabs/php-github-api#420]
Even after that fix was merged, stuff is still broken:

![image](https://cloud.githubusercontent.com/assets/2829600/17287722/37ab8c00-57c9-11e6-8fc9-1b8488feaaaf.png)

**Comment by Nyholm** [comment]
For the record: This will be fixed by https://github.com/php-http/client-common/pull/35

**Comment by Nyholm** [comment]
Is this till an issue? Can it be closed?
