### ISSUE TITLE
Use Symfony/options-resolver

### ISSUE THREAD

**Issue by Nyholm** [KnpLabs/php-github-api#421]
Since #419 we have 3 constructor arguments. It is likely that a new feature will require a 4th one. It could be better to use an array instead. Especially for string/bool arguments. 

```php
$client = new Client($httpClient, ['api_version'=>'s2', 'enterprice_url'=>'foobar'])
```

These should be validated with the symfony option resolver and then stored an separate instance variables (like today)

**Comment by GrahamCampbell** [comment]
Nah, I think that's overkill, and we'd likely want to avoid adding more stuff to the constructor anyway. I can't think of any use cases?

**Comment by Nyholm** [comment]
It may be overkill. But it is more future proof. Maybe this can be saved to 3.0 if we notice that we have 5+ constructor arguments.
