### ISSUE TITLE
Support per_page param on paginated resources

### ISSUE THREAD

**Issue by syropian** [KnpLabs/php-github-api#430]
Per the Github API docs on [pagination](https://developer.github.com/guides/traversing-with-pagination/)

> By passing the per_page parameter, you can specify how many items you want each page to return, up to 100 items.

Is this currently possible? I didn't see it within the `Result Pager` docs.

I could probably create a PR for this if no one else wants to tackle it. 

**Edit:** I didn't check every resource, but I noticed `starring()->all()` only supports a page param. It's actually a little odd that a function called `all()` only returns one page, not all stars. However, since it's common practice to use the `Result Pager` for this, it seems like that function could use a rename. ¯\_(ツ)_/¯

**Edit 2:**: I see `per_page` is actually implemented in the `AbstractAPI.php` class, but not all functions accept `per_page` as a param.

**Comment by mcharytoniuk** [comment]
It would be especially useful in `api('repo')->branches(...)`. I am working on a big project with >30 branches and this parameter is not supported.

**Comment by acrobat** [comment]
We don't need these parameters on each api method, instead you should use the [ResultPager](https://github.com/KnpLabs/php-github-api/blob/7b84f9cf8c44c7036b0573055215404385e8a5b1/doc/result_pager.md). This class automatically adds the correct per_page and page parameters and allows you to fetch all records or loop over them page by page.
