### ISSUE TITLE
Support for newly-shipepd feature: Projects

### ISSUE THREAD

**Issue by Geolim4** [KnpLabs/php-github-api#437]
Hello,

Recently Github shipped a new feature: Projects
Is there a pull request/update coming ?
Else i can handle this :)

Cheers,
Georges

**Comment by cursedcoder** [comment]
Yeah feel free to contribute that @Geolim4

**Comment by Geolim4** [comment]
Ok got it :)

**Comment by Geolim4** [comment]
Did i absolutely need to provide tests with the new API endpoints ?
I'm not a regular user of PhpUnit so I'm not sure how to make them work without broking the build.

**Comment by cursedcoder** [comment]
@Geolim4 I think tests with mocks are enough.
You can take any other tests as a pattern, as they all very similar.
If anything breaks we will help you.
