### ISSUE TITLE
Do we need our RuntimeException?

### ISSUE THREAD

**Issue by Nyholm** [KnpLabs/php-github-api#447]
Are we expecting someone to catch our RuntimeException? I suggest removing it.

**Comment by GrahamCampbell** [comment]
I use it. :P

**Comment by Nyholm** [comment]
Okey. Is there a reason why you don't catch \RuntimeException or \Github\Exception\ExceptionInterface?

If so, I'm happy to close this issue.

**Comment by GrahamCampbell** [comment]
Not all exceptions extend runtimeexception here.

**Comment by Nyholm** [comment]
Of course. 
I was reviewing the exceptions and there are too many undefined ones. (Or unclear)

I was thinking that one could split them up into two groups. "Before we send a request"-exception and "request and after request"-exception. 

That would mean that we would have exceptions more specific than ErrorException. 

This change would only affect the base exception (the once we inherit from). 


There is of course a change that I'm way wrong here or that we think it is too late for such change

**Comment by Nyholm** [comment]
I did not find anything that I strongly think we should change. 

Thank you for the feedback.
