### ISSUE TITLE
202 response code

### ISSUE THREAD

**Issue by mdkholy** [KnpLabs/php-github-api#455]
Some API endpoints like [repo statistics endpoints](https://developer.github.com/v3/repos/statistics/#a-word-about-caching) may send a `202 Accepted` response code which means that Github has accepted the request, but the processing has not been completed. Is there a way I could fetch the response status code and act upon it? Another possible workaround is to add an http plugin that detects those `202` response codes, sleeps for a few moments and then re-sends the request. Thanks!

> Computing repository statistics is an expensive operation, so we try to return cached data whenever possible. If the data hasn't been cached when you query a repository's statistics, you'll receive a 202 response; a background job is also fired to start compiling these statistics. Give the job a few moments to complete, and then submit the request again. If the job has completed, that request will receive a 200 response with the statistics in the response body.

Source: https://developer.github.com/v3/repos/statistics/#a-word-about-caching

**Comment by Nyholm** [comment]
Hm, you could always use `GitHub::getLastResponse()->getStatusCode()`. That would give you the status code for the last response.

**Comment by mdkholy** [comment]
Ah, thanks! that should do it ;-)

**Comment by anil2604** [comment]
Sometimes/repos/{owner}/{repo}/stats/code_frequency API returns a 202 status code and the response was black so how can I get a response with a 200 status codes in this API?
