### ISSUE TITLE
Get a single public key

### ISSUE THREAD

**Issue by lbausch** [KnpLabs/php-github-api#467]
https://developer.github.com/v3/users/keys/#get-a-single-public-key

Is this already possible with the latest version?

**Comment by acrobat** [comment]
It is possible by using the currentuser api.

```php
$key = $client->user()->keys()->show(1234);
```

I've created a PR #478 to add the missing docs for this api.

**Comment by lbausch** [comment]
I used `$client->me()->keys()->show('1234');` and this worked perfect. Thank you :)
