### ISSUE TITLE
Allow getting README contents in different formats

### ISSUE THREAD

**Issue by BR0kEN-** [KnpLabs/php-github-api#474]
For now, with API v3, we can get the contents of `README.md` in `raw` format or as rendered `html`. To do so request should contain `Accept` header with one of values described in documentation: https://developer.github.com/v3/repos/contents/#custom-media-types.

My proposition - is to add the third argument (`$format = 'raw'`) to the `readme()` method of `\Github\Api\Repo` class and empower the request with necessary header.

**Comment by Nyholm** [comment]
This can be closed.

**Comment by BR0kEN-** [comment]
PR is merged, - so yep, can be. Thanks.
