### ISSUE TITLE
2.0 stable release

### ISSUE THREAD

**Issue by acrobat** [KnpLabs/php-github-api#476]
Is there an eta of when we can expect the 2.0 stable release? Or is there a issue/milestone with work left before a stable release? I would be able to help and finish the release

Thanks!

**Comment by Nyholm** [comment]
I've been talking around with people at SymfonyCon last week. We all want to see a stable version. I will go though all issues, PRs and make a code review to see if we are ready. I will do this as soon as possible (today or tomorrow). Please do the same and we can see if we have the same result.

**Comment by acrobat** [comment]
Ok, I will try to make some time for it! Thanks for the quick reply!

**Comment by Nyholm** [comment]
I want to investigate if #447 is a good idea. 
I would also like to send a PR for #461

**Comment by Nyholm** [comment]
As far as I can see; my PR #480 is the only blocker for tagging a new release candidate. That RC will most likely to be the last one

**Comment by Nyholm** [comment]
#472 removes some code. After that we are good to go =)

**Comment by GrahamCampbell** [comment]
Probably an idea to deal with https://github.com/KnpLabs/php-github-api/pull/481 too.

**Comment by Nyholm** [comment]
Agreed. @cursedcoder is usually working in batches. (right now is such batch). I think #481 is included in this batch. =)

**Comment by acrobat** [comment]
[2.0.0 is released](https://github.com/KnpLabs/php-github-api/releases/tag/2.0.0)
