### ISSUE TITLE
2.0 Release Broke Setting The Version

### ISSUE THREAD

**Issue by GrahamCampbell** [KnpLabs/php-github-api#486]
Worked on 2.0.0-RC4, broken on 2.0.0.

**Comment by GrahamCampbell** [comment]
I'm still passing the API version as parameter 2 to the Client's constructor, but now it doesn't get set. There are literally no other code changes. If I revert the upgrade, then it works.

The upgrade commit in the wrapper library for reference: https://github.com/GrahamCampbell/Laravel-GitHub/commit/23fb9dea6f13f072dc38791ad3b67650e1238432.

**Comment by Nyholm** [comment]
Can you confirm that #487 fixes you issue?

**Comment by GrahamCampbell** [comment]
Will do tomorrow. Need to sleep. :)

**Comment by GrahamCampbell** [comment]
Yes, I can confirm your PR fixes the issue.
