### ISSUE TITLE
Conditional requests?

### ISSUE THREAD

**Issue by m1guelpf** [KnpLabs/php-github-api#492]
Does this api support [Conditional Requests](https://developer.github.com/v3/#conditional-requests)?
If it doesn't, how can I try to add it?
It's a great feature that allows to increase the rate limit.

**Comment by Nyholm** [comment]
Sure, have a look at https://github.com/KnpLabs/php-github-api#cache-usage

**Comment by Kyslik** [comment]
Any progress on this?

**Comment by m1guelpf** [comment]
@Kyslik Yep, it integrates automatically.
