### ISSUE TITLE
Trying to merge a PR : Base branch was modified. Review and try the merge again.

### ISSUE THREAD

**Issue by arsenik** [KnpLabs/php-github-api#497]
Getting sha from master

```php
<?php 
$branch = $this->github_client->api('repo')->branches(
	$this->github_owner,
	$this->github_repo, 'master'
);
$sha = $branch['commit']['sha'];
?>
```
Creating a branch from master with
```php
<?php 
$this->github_client->api('git_data')->references()->create(
	$this->github_owner, 
	$this->github_repo, array(
		'ref' => 'refs/heads/'.$this->deploy_branch,
		'sha' => $sha
));
?>
```
Removing a file
```php
<?php 
$this->github_client->api('repo')->contents()->rm(....) 
?>
```
Create a PR
```php
<?php 
$this->pr = $this->github_client->api('pr')->create(
	$this->github_owner, 
	$this->github_repo, array(
		'title' => $message,
		'base' => 'master',
		'head' => $this->deploy_branch,
		'body' => $message
)); 
?>
```
Merge PR, I get ```Base branch was modified. Review and try the merge again.``` 
```php
<?php 
$this->github_client->api('pr')->merge(
	$this->github_owner, 
	$this->github_repo, 
	$this->pr['number'],
	$message, 
	$this->pr['head']['sha']
);
?>
```

Base branch is master and I just created a branch from it at the beginning, how come it can be modified if no one pushed anything on master during this process?

**Comment by chrisryan10** [comment]
Did you ever solve this problem?

**Comment by lukepolo** [comment]
I also have been having this problem

**Comment by redmice** [comment]
Did you stashed your feature branch before merging?

**Comment by acrobat** [comment]
I'm closing this issue for now, as it seems that the error is not related to this library. Please consult the github docs for more information, otherwise create a new issue if the bug is in this library. Thanks!
