### ISSUE TITLE
Question about a problem with v. 2 cache - missing cache files

### ISSUE THREAD

**Issue by ksdev-pl** [KnpLabs/php-github-api#502]
Hi

A v. 2.0.1 noob question:

In the v. 1.*  to use the cache I've used:

```php
$githubClient = new \Github\Client(
    new \Github\HttpClient\CachedHttpClient(['cache_dir' => storage_path('app/cache')])
);

$paginator = new \Github\ResultPager($githubClient);

// The rest of the code with requests
```

I see the cache files using this code, so I know they are created.

In the v. 2 I've tried the `php-cache/filesystem-adapter`:

```php
use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;
use Cache\Adapter\Filesystem\FilesystemCachePool;

// ...

$filesystemAdapter = new Local(storage_path('app')); // storage_path: laravel method pointing to "app" storage folder
$filesystem        = new Filesystem($filesystemAdapter);

$pool = new FilesystemCachePool($filesystem);

$client = new \Github\Client();
$client->addCache($pool);

$paginator = new \Github\ResultPager($client);

// The rest of the code with requests - exactly the same as for the 1.*
```

The end result is the same as in the v 1.* - that is, I'm successfully downloading a list of gists from github. During debugging I've checked that the cache plugin is added correctly.

The difference is - in the v. 2, with the code as seen above, no cache files are created. 

The path is correct, because a "cache" folder is created in laravel storage app folder - but it's empty.

I've tried also with `madewithlove/illuminate-psr-cache-bridge`. The code with it is somewhat different (the folder path is configured in laravel config), the end result is correct and without errors (I'm downloading a list of gists), but I don't see the cache files, they are not created.

What am I missing? Or how to debug it, any help with where to check what the problem is?

**Comment by Nyholm** [comment]
Thank you for a detailed issue. I've copied your code and tested it myself. It all seams to work properly. 

The only thing I'm not familiar with is `storage_path`. I replaced it with 
```php
$filesystemAdapter = new Local(__DIR__);
```
This will create a cache folder next to the current file. In that cache folder there your cache files will appear. (Be aware that IDEs could be quite slow in showing new files.)

**Comment by ksdev-pl** [comment]
Thank you for the answer. I will test it later again and I'll let you know.

**Comment by ksdev-pl** [comment]
I've made more tests:

When I'm not authenticating, this code produces a cache file:

```php
$filesystemAdapter = new Local(storage_path('app'));
$filesystem        = new Filesystem($filesystemAdapter);

$pool = new FilesystemCachePool($filesystem);

$client = new \Github\Client();
$client->addCache($pool);

$paginator = new \Github\ResultPager($client);

// $client->authenticate($token, null, \Github\Client::AUTH_HTTP_TOKEN);

$gistsApi = $client->api('gists');

$rawUserGists = $paginator->fetch($gistsApi, 'all');
```

But when I add authentication, no cache file is created:

```php
$filesystemAdapter = new Local(storage_path('app'));
$filesystem        = new Filesystem($filesystemAdapter);

$pool = new FilesystemCachePool($filesystem);

$client = new \Github\Client();
$client->addCache($pool);

$paginator = new \Github\ResultPager($client);

$client->authenticate($token, null, \Github\Client::AUTH_HTTP_TOKEN);

$gistsApi = $client->api('gists');

$rawUserGists = $paginator->fetch($gistsApi, 'all');
```

In both cases the end result is correct and without errors, the gists are downloaded.

Am I doing something wrong? What can be the reason of missing cache files with authentication? Or how can I debug it to narrow down the problem?

**Comment by Anahkiasen** [comment]
Same issue here, as far as I can see cache is not created when authenticated

**Comment by Anahkiasen** [comment]
It seems the issue is [this line](https://github.com/php-http/cache-plugin/blob/master/src/CachePlugin.php#L188) in the HTTP CachePlugin, since all Github responses return the `private` Cache-Control directive, nothing is ever cached. 

But that directive is only for shared caches, you _are_ allowed to cache the response into a private cache, which is my usecase.

Related issue on php-http's end https://github.com/php-http/plugins/issues/58

**Comment by acrobat** [comment]
Hmm this indeed explains the problem I have that nothing is cached, hopefully we have some kind of solution soon!
