### ISSUE TITLE
EnterpriseUrl Prepend Path causes bad URI's

### ISSUE THREAD

**Issue by Nilithus** [KnpLabs/php-github-api#511]
Hello

I'm using version `2.0.1` and we have an github enterprise url so I'm creating my client as
```php
$client = new Github\Client(null, null, 'http://enterpriseUrlHere');
```

However I think there seems to be a bug [here](https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Client.php#L318). The `PathPrepend` Plugin adds `/api/%s/` Which when requests are made will create bad uri's. Such as `http://enterpriseGithub/api/v3//repo/....` Note the `//`. When I changed `/api/%s/` to `/api/%s` it seemed to fix the issue.

**Comment by Nyholm** [comment]
Thank you @Nilithus. You are correct. I have created a PR to fix this issue
