### ISSUE TITLE
List members of an Org

### ISSUE THREAD

**Issue by jdc1898** [KnpLabs/php-github-api#512]
I wanted to see if someone could add the following to the Organization.php file?

`    
    /**
     * Get organization memberships by its name.
     *
     * @link https://developer.github.com/v3/orgs/members/#members-list
     *
     * @param string $organization the organization to show
     *
     * @return array information about the organization
     */
    public function showOrganizationMembers($organization)
    {
        return $this->get('/orgs/'.rawurlencode($organization).'/members');
    }
`

**Comment by acrobat** [comment]
Hi @jdc1898, this method is already included in the api. See [Organization/Members](https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/Organization/Members.php#L13)

@Nyholm this issue can be closed!

**Comment by Nyholm** [comment]
Thank you @acrobat for a good answer
