### ISSUE TITLE
Status API and Review API

### ISSUE THREAD

**Issue by Dgame** [KnpLabs/php-github-api#514]
I would like to see support for the [status API](https://developer.github.com/v3/repos/statuses/) as well as (as soon as finished) the [review API](https://developer.github.com/v3/pulls/reviews/). Is it possible to get that in the near future? :)

**Comment by xabbuh** [comment]
I have a working draft for the PR reviews API locally. I will create a PR for it during this weekend.

**Comment by Dgame** [comment]
Any progress on this matter? I could help if you want.

**Comment by m1guelpf** [comment]
I could also help.

**Comment by xabbuh** [comment]
Ah sorry, I forgot to create the PR. You can have a look at an earlier state of the draft at https://github.com/xabbuh/php-github-api/tree/review-api. I will push the latest changes when I am back home tonight and create the PR then.

**Comment by xabbuh** [comment]
see #517

**Comment by Dgame** [comment]
Nice. The only thing that I'm missing now is the Status API. :)

**Comment by acrobat** [comment]
@Dgame I think this issue can be closed as the [status api is already implemented](https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/Repository/Statuses.php)

**Comment by Dgame** [comment]
Oh, how could I overlook this? 😄  Thank you.
