### ISSUE TITLE
Add "Find installations" wrapper to Integrations

### ISSUE THREAD

**Issue by offsky** [KnpLabs/php-github-api#516]
There is an API call you can make to fetch your installations. 

`GET /integration/installations`
Referenced here: https://developer.github.com/v3/integrations/

This can easily be added to Api/Integrations.php by adding these lines:

```
public function findInstallations()
    {
        return $this->get('/integration/installations');
    }
```
I realize that this can be accomplished using the generic `$github->getHttpClient()->get('integration/installations')`, but this convenience method would be nice.

**Comment by m1guelpf** [comment]
@offsky Why don't you make a PR?

**Comment by Nyholm** [comment]
I would be happy to see a PR like that.

**Comment by offsky** [comment]
I am sorry, but I dont have time right now to make a PR, but I'll put it on my to-do list.

**Comment by acrobat** [comment]
I've added this method in #527
