### ISSUE TITLE
Gist pagination, returning all gists?

### ISSUE THREAD

**Issue by shawnsandy** [KnpLabs/php-github-api#521]
I have been trying to use the `result_pager` to paginate links but it seem I can never get all my gist. What am I missing here??? how can I get to list 100+ (all if possible) gist results.

Any help appreciated
Thanks

**Comment by acrobat** [comment]
I've tested the `ResultPager` with a large list of gists and it works as expected. I can fetch all records and get correct pagination to fetch them page by page.

```php
$paginator  = new Github\ResultPager($client);
$result = $paginator->fetchAll($client->gist(), 'all');
```
