### ISSUE TITLE
View GitHub response headers

### ISSUE THREAD

**Issue by offsky** [KnpLabs/php-github-api#526]
When GitHub responds to a request, they set headers in the response that tell you the current rate limiting values as well some information about scopes.

https://developer.github.com/v3/oauth/#scopes
https://developer.github.com/v3/#rate-limiting

It would be nice if there was a way to get this information from this library.

**Comment by acrobat** [comment]
If you just want to view this info, you could add a logger to the builder class. This way you will receive the full request info in the logs

```
$builder->addPlugin(new LoggerPlugin($logger, new \Http\Message\Formatter\FullHttpMessageFormatter()));```
see: http://docs.php-http.org/en/latest/plugins/logger.html

**Comment by Nyholm** [comment]
Awesome. @offsky would you mind sending a PR?
