### ISSUE TITLE
New minor release

### ISSUE THREAD

**Issue by Nyholm** [KnpLabs/php-github-api#530]
Are we ready to make a new minor release? What else do we want to include?

**Comment by acrobat** [comment]
If possible I would like to wait for a new release of the php-http/cache-plugin and merge #531. This way caching is fixed in the new minor release!

**Comment by Nyholm** [comment]
We could always do two minor releases =)

**Comment by acrobat** [comment]
Nevermind than :D

**Comment by m1guelpf** [comment]
@Nyholm So then, when are you going to tag a new minor release?

**Comment by Nyholm** [comment]
Yes. I started to prepare but got interrupted. Will do tomorrow

**Comment by Nyholm** [comment]
Just a few minutes away. Will then merge some PRs and make 2.3. 

See #542

**Comment by m1guelpf** [comment]
@Nyholm Thank you! Just updated OrgManager to use the new version.
