### ISSUE TITLE
Example to POST to any route?

### ISSUE THREAD

**Issue by bobeagan** [KnpLabs/php-github-api#537]
I've been struggling to figure out how to create a [POST request to a non-supported route](https://github.com/KnpLabs/php-github-api/blob/master/doc/request_any_route.md) (pull request review request) basedon  and have been getting cryptic error messages from GitHub with what I have so far:

```
$requests['reviewers'][] = 'test-user';

$githubClient = new \Github\Client(null, 'black-cat-preview');
$githubClient->authenticate($secret, Github\Client::AUTH_HTTP_TOKEN);
$githubClient->getHttpClient()->post('/repos/' . $payload->repository->full_name . '/pulls/' . $payload->pull_request->number . '/requested_reviewers', $requests);
```

Returns: `Invalid request.  For 'links/0/schema', nil is not an object.`

**Comment by m1guelpf** [comment]
@bobeagan You can:
1. Check the code for the endpoint: There are some undocumented methods.
2. Make a PR adding that endpoint

**Comment by bobeagan** [comment]
[Review requests](https://developer.github.com/v3/pulls/review_requests/) are different than reviews, I've already checked the code and support for it does not exist.  While I could make a PR, I'm really just looking to clarify and see an example of how to perform a POST using `getHttpClient()->post()`.

**Comment by m1guelpf** [comment]
@bobeagan The GetHTTPClient code is https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/HttpClient/Builder.php#L93

**Comment by bobeagan** [comment]
For anyone that runs up against this in the future, the parameters for the `getHttpClient->post()` are `uri, `headers` and then `body`.  You need to send an empty array as the second (headers) parameter and then remember to `json_encode` your third (body) parameter.

The end result looks like:
`$githubClient->getHttpClient()->post('/repos/' . $payload->repository->full_name . '/pulls/' . $payload->pull_request->number . '/requested_reviewers', [], json_encode($requests));`
