### ISSUE TITLE
setPerPage doesn't work in some cases

### ISSUE THREAD

**Issue by offsky** [KnpLabs/php-github-api#538]
This doesn't work: 
```
$api = $client->api('users');
$api->setPerPage(100);
$response = $api->all($since);
```
The reason is because the api adds a "?since=1234" to the path and then another "?per_page=100" is added to the path to make an invalid url. The second ? should be an &.

Here is the solution:
AbstractAPI.php::get()

```
...
if (count($parameters) > 0) {
            if(strpos($path,"?")===false) {
                $path .= '?'.http_build_query($parameters);
            } else {
                $path .= '&'.http_build_query($parameters);
            }
}
...
```

Pull request incomming

**Comment by Nyholm** [comment]
Thank you for this issue. 

May I propose an alternative solution. In `User::all()` we should use parameters instead of using inline query.. 

```php
// Current
return $this->get('/users?since=' . rawurldecode($id));
// new
return $this->get('/users', ['since' => rawurldecode($id)]);
```
