### ISSUE TITLE
Trailing slash in enterprise url breaks query, fixed in master but exists in tag 2.0.1

### ISSUE THREAD

**Issue by whoacowboy** [KnpLabs/php-github-api#540]
The trailing slash is messing up the query in tag 2.0.1

[Tag 2.0.1](https://github.com/KnpLabs/php-github-api/blob/2.0.1/lib/Github/Client.php#L318)

        $builder->addPlugin(new PathPrepend(sprintf('/api/%s/', $this->getApiVersion())));

[Master](https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Client.php#L324) works

        $builder->addPlugin(new PathPrepend(sprintf('/api/%s', $this->getApiVersion())));

**Comment by Nyholm** [comment]
Yes, correct. You are asking for a new tag, right?

**Comment by whoacowboy** [comment]
That would be great, thanks.

**Comment by Nyholm** [comment]
New tag is coming up within a few minutes. See #542
