### ISSUE TITLE
Question about cache

### ISSUE THREAD

**Issue by demianchuk** [KnpLabs/php-github-api#541]
Hi,

In docs there is next info: "Using cache, the client will get cached responses if resources haven't changed since last time"

What does it mean: "resources have not changed"?
In which time cache will be expired?
Is it possible to set ttl parameter via some setter?

Thanks

**Comment by GrahamCampbell** [comment]
> What does it mean: "resources have not changed"?

A web server can respond with "304 Not Modified".

> Is it possible to set ttl parameter via some setter?

👎 for allowing setters. I think our objects should be immutable, configured at construction.

**Comment by GrahamCampbell** [comment]
> A web server can respond with "304 Not Modified".

In fact, further to this, in the case of GitHub, requests that result in a 304 response won't count towards your rate limit.

**Comment by demianchuk** [comment]
Ok, thanks for answer. 
But as for me it would still good to have some possibility to set max ttl via configuration
