### ISSUE TITLE
Make sure configure returns $this

### ISSUE THREAD

**Issue by Nyholm** [KnpLabs/php-github-api#549]
We need to make sure all our `configure()` calls returns `$this`. 

This is blocked by #532

**Comment by bobeagan** [comment]
I believe this should be good, the only `configure()` that doesn't is in the AbstractApi https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/AbstractApi.php#L37

**Comment by Nyholm** [comment]
Thank you!
