### ISSUE TITLE
SERIOUS BUG IN NEW VERSION

### ISSUE THREAD

**Issue by GrahamCampbell** [KnpLabs/php-github-api#557]
Requests are being cached incorrectly, so that API calls to get a users repo are now returning cached results from the wrong user. I am rolling back to the previous version immediately.

**Comment by acrobat** [comment]
I think the generated cache key is to general. See https://github.com/php-http/cache-plugin/blob/master/src/CachePlugin.php#L290

If the request parameters are included the key will be unique enough I think

Thoughts on this @Nyholm?

**Comment by GrahamCampbell** [comment]
This is only in the very latest update. No such bug occurred 7 days ago.

**Comment by acrobat** [comment]
That's because the caching of requests was broken in previous versions. All requests with the private or no-cache directive were skipped by the cache plugin. So no github api request could be cached

You can fix this for now by passing this option to the cache plugin. Example from the docs:

```
use Cache\Adapter\Redis\RedisCachePool;

$client = new \Redis();
$client->connect('127.0.0.1', 6379);
// Create a PSR6 cache pool
$pool = new RedisCachePool($client);

$client = new \Github\Client();
$option = [ 'respect_response_cache_directives' => ['no-cache', 'private', 'max-age', 'no-store']];
$client->addCache($pool, $options);
```

**Comment by acrobat** [comment]
@GrahamCampbell Can you provide some example call which fails when using the cache? So I can check how to fix this

**Comment by Nyholm** [comment]
Thank you for reporting this. I will make a PR.

**Comment by Nyholm** [comment]
I've added #558. Please review it. 

We are just waiting for a new tag on the CachePlugin.

**Comment by GrahamCampbell** [comment]
Also, the current version of this package is throwing a deprecation error, even know I'm not using a deprecated feature?

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-GitHub/blob/master/src/GitHubFactory.php#L86

**Comment by Nyholm** [comment]
>Also, the current version of this package is throwing a deprecation error, even know I'm not using a deprecated feature?

From where?

**Comment by GrahamCampbell** [comment]
It's because you set a deprecated default: https://github.com/php-http/cache-plugin/blob/v1.3.0/src/CachePlugin.php#L336,

**Comment by GrahamCampbell** [comment]
Surely this still won't fix everything. Shouldn't the caching have only been etag based, why on earth would we provide a correct etag, and then fetch the wrong cache response?
