### ISSUE TITLE
What's the best way of calling a full URL you get back from GitHub within this API?

### ISSUE THREAD

**Issue by DaveBagler** [KnpLabs/php-github-api#560]
For example, if you use this API to get a list of Project Cards you receive back the card information and the URL of the issue.

Currently, I'm parsing the URL to get the org/user, repo and issue id and then using these three pieces of information to make a call get the issue using this API to get the issue details.  However, this approach is no recommended by GitHub (https://developer.github.com/guides/best-practices-for-integrators/#dont-manually-parse-urls).

I'd like just to call the URL I receive from the GitHub API, but I'm not sure how to do that within this API.

**Comment by acrobat** [comment]
Hi @DaveBagler 

By requesting the httpClient itself you can call any url. See the docs for [`Request any Route`](https://github.com/KnpLabs/php-github-api/blob/master/doc/request_any_route.md)

**Comment by DaveBagler** [comment]
Oh that's nice and easy. Thanks!
