### ISSUE TITLE
Documented example is wrong for List all milestones

### ISSUE THREAD

**Issue by tmulry** [KnpLabs/php-github-api#573]
https://github.com/KnpLabs/php-github-api/blob/master/doc/issue/milestones.md#list-milestone-labels

This call should end in `->all($owner, $repo)` instead of `->labels($owner, $repo)`

**Comment by m1guelpf** [comment]
@tmulry Why don't you submit a PR?

**Comment by tmulry** [comment]
Done, #574

**Comment by bobeagan** [comment]
I believe this to be a non-issue.  See https://github.com/KnpLabs/php-github-api/pull/574#issuecomment-296758983
