### ISSUE TITLE
ComposerCI Beta

### ISSUE THREAD

**Issue by m1guelpf** [KnpLabs/php-github-api#583]
You migth benefy from ComposerCI, a new tool I'm building to get pull requests every time a new dependency update is released. If KnpLabs wants to enter the beta, please [register for the beta](https://composerci.miguelpiedrafita.com?ref=knplabs-phpgithubapi-issue), and I'll be happy to send you an invite. After all, ComposerCI uses this client to provide core features!
Thank you!

**Comment by GrahamCampbell** [comment]
👎 I don't like the idea of services that update the version constraints to new breaking versions. Updating dependencies yourself is fine as far as I'm concerned.

**Comment by m1guelpf** [comment]
@GrahamCampbell 
> Updating dependencies yourself is fine as far as I'm concerned.

Unless you don't notice a new release... Anyway, lots of people like and use [Greenkeper](https://greenkeeper.io), so I believe a composer version would help people... In the final version, I'll try to show release notes & the commit range. The idea is to warn the developer about the new version, so he/she can decide if upgrading is a good option.

**Comment by GrahamCampbell** [comment]
> Anyway, lots of people like and use Greenkeper

Yeh, as expected, I hate that too. :P
