### ISSUE TITLE
Native support for the retry plugin

### ISSUE THREAD

**Issue by GrahamCampbell** [KnpLabs/php-github-api#590]
It is my understanding (from the docs, without looking in much detail at the code), that the retry plugin will need to be registered before the GithubExceptionThrower.

I am looking to retry error 5xx, and 404 responses from GitHub. 5xx, for obvious reasons, and 404, because of race conditions from GitHub where they fire webhooks before data has persisted on their systems, so I need to retry the request, and would like if this was done automatically by a plugin, and since the retry plugin already exists, it would be nice to be able to easily use it.

**Comment by Nyholm** [comment]
No. The other way around. The first plugin is the one that is executing the request first and handling the response last. The RetryPlugin is only taking care of the response and you want it to be as close to the internet/httpclient as possible. You should put it at the end of the chain.

**Comment by GrahamCampbell** [comment]
The docs look wrong then. :P

**Comment by Nyholm** [comment]
Which docs? Can you give a link and I'll make sure to update.

**Comment by GrahamCampbell** [comment]
http://docs.php-http.org/en/latest/plugins/retry.html

**Comment by GrahamCampbell** [comment]
Ping @Nyholm.
