### ISSUE TITLE
[RFC] HHVM support

### ISSUE THREAD

**Issue by acrobat** [KnpLabs/php-github-api#599]
I'm opening the discussion on what we should do with HHVM. A lot of projects are dropping HHVM lately, symfony, twig, swiftmailer, etc... (see https://twitter.com/fabpot/status/865263458903875584) and laravel (https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0)

I'm not really in favor of dropping HHVM but current travis ci does not support HHVM on ubuntu precise anymore

> HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.

So what should we do about this? Refactor our build config to use trusty or move hhvm to allowed failures and drop hvvm support?

/cc @Nyholm

**Comment by Nyholm** [comment]
I think we should drop support only when we have major issues with it. (Like Symfony had)

Currently I think we should just modify our Travis config to run trusty on the hhvm build.

**Comment by acrobat** [comment]
Ok! I will create a PR for this
