### ISSUE TITLE
Refactor Repo Commits Compare method

### ISSUE THREAD

**Issue by bobeagan** [KnpLabs/php-github-api#602]
The `compare` method in https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/Repository/Commits.php currently accepts a `mediaType` parameter to change the Accept header.  It seems like this should have a `configure()` method that handles this, which would follow the pattern of how it is handled elsewhere in the library.

This would be a breaking-change and should be targeted for the next major release.

**Comment by acrobat** [comment]
I don't know actually if we should change this. I like the fact that the mediatype change is only for that specific method and doesn't change it for the whole object (and all api calls in it) like `AcceptHeaderTrait` and `configure` method would do.

So I'm more in favour of keeping it this way.

**Comment by bobeagan** [comment]
I'm not invested in this request enough to argue one way or the other for it. Will close.
