### ISSUE TITLE
Compare two branches in a repository

### ISSUE THREAD

**Issue by benoitdelasseaux** [KnpLabs/php-github-api#614]
Hello,

I'm actually using your client for a project and i saw in the github API that we can get informations about comparing two branches.

Does your client support this too? If yes can you tell me how can i get these informations?

**Comment by Nyholm** [comment]
Hey. That is great. If it is in our docs then we support it for sure.

**Comment by benoitdelasseaux** [comment]
i don't see this in your docs unless i don't see it.

In this case do you think you will develop it in a next future?

**Comment by m1guelpf** [comment]
@benoitdelasseaux Coule you link to the api docs page?

**Comment by benoitdelasseaux** [comment]
yes sure

https://developer.github.com/v3/repos/commits/

And with Postman when I answer the API i get this type of result:

htttpRequest: https://api.github.com/repos/:org/:repo/compare/:branch1...:branch2?access_token=...

Response =>
....
    "status": "diverged",
    "ahead_by": 9,
    "behind_by": 474,
    "total_commits": 9, 
...

**Comment by m1guelpf** [comment]
@benoitdelasseaux Here it is!
https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/Repository/Commits.php#L18-L26

**Comment by benoitdelasseaux** [comment]
Nice!

Sorry for my mistake :)

I'll investigate now.
Thanks for your help 

I close this issue
