### ISSUE TITLE
Review Requests endpoints under preview

### ISSUE THREAD

**Issue by bobeagan** [KnpLabs/php-github-api#621]
https://developer.github.com/v3/pulls/review_requests/

- Need to update the `configure()` method to set the `Accept` header
- Should check on why the `all()` method has a `$params`
  - Doesn't appear to be anything in the docs that can be set
- Need to figure out if a short-term, backwards-compatible change should be made to `create()` and `remove()`
  - By adding a `$teamReviewers` parameter and setting the default value of `$reviewers` to an empty array
  - How to handle different shapes for preview vs not preview?
- Ideally, we would just remove the `['reviewers' => $reviewers]` and make it take a more generic `$params`
  - To protect from any future changes and to more closely follow the pattern of other endpoints
  - Putting the responsibility on the developer to implement the correct information

**Comment by acrobat** [comment]
I've created a PR to address most of these remarks, see #984. Only the last remark is not implemented as it is "ok" for now and otherwise can be addressed in a separate PR to handle all these cases.
