### ISSUE TITLE
Mistake in Issue -> comments docs

### ISSUE THREAD

**Issue by inkarasdev** [KnpLabs/php-github-api#626]
Currently it says that method to update an issue comment is accessed via 'create', that is not correct and results in "Not Found" when used. 
Update works fine with ->update() method though.

Wrong: "$client->api('issue')->comments()->create('KnpLabs', 'php-github-api', 33793831, array('body' => 'My updated comment'));"

Correct: "$client->api('issue')->comments()->update('KnpLabs', 'php-github-api', 33793831, array('body' => 'My updated comment'));"

**Comment by Einenlum** [comment]
Thanks @inkarasdev for your feedback. Could you please do a PR to fix it?

**Comment by viion** [comment]
This was fixed on 8th August: https://github.com/KnpLabs/php-github-api/commit/09149c710b5f342a438ef967962e348a9664913b#diff-837c3b7365b614d770b4a1f5a0a59e14

**Comment by Einenlum** [comment]
Oh indeed. Then I think we can just close this issue.
