### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by m1guelpf** [KnpLabs/php-github-api#629]
Hi!

A recent commit added support for GraphQL variables, and this would be very useful in the project I'm developing.

Could you please tag a new release, so we can pull this change from Composer?

Thank you!

:octocat:

**Comment by acrobat** [comment]
@Nyholm can I just tag a new release (after updating the changelog)? Or do I need to do something extra?

**Comment by Nyholm** [comment]
Before I release I do always: 
1: Check the diff from last release (https://github.com/KnpLabs/php-github-api/compare/2.5.0...master)
2: Decide if it is a minor or a patch release (minor in this case, right?)
3: Make sure the change log is up to date
4: Make sure the branch alias is at least the same as the version Im going to release. (Note this https://github.com/KnpLabs/php-github-api/pull/609#issuecomment-311019335)
5: Then I create a new release from the GUI: https://github.com/KnpLabs/php-github-api/releases/new

**Comment by acrobat** [comment]
Thanks @Nyholm for the release checklist! I will tag a new release!

**Comment by acrobat** [comment]
@m1guelpf I've released 2.6.0! See https://github.com/KnpLabs/php-github-api/releases/tag/2.6.0
