### ISSUE TITLE
Client setEnterpriseUrl method is private

### ISSUE THREAD

**Issue by jacobtruman** [KnpLabs/php-github-api#636]
The documentation for using the Enterprise API (https://github.com/KnpLabs/php-github-api/blob/master/doc/enterprise.md) says you can set the enterprise URL like this:

$client->setEnterpriseUrl('https://ghe.host');

This fails because the method is private:

https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Client.php#L331

**Comment by acrobat** [comment]
This is indeed an issue with the docs as the enterprise url should be passed to the [client constructor](https://github.com/KnpLabs/php-github-api/blob/ccf4ed77c869b99461ac18f768c2b6c08c585ea1/lib/Github/Client.php#L122)

So if you can please open a PR to fix the specific docs. Thanks!

**Comment by acrobat** [comment]
Fixed in #649
