### ISSUE TITLE
Search pagination

### ISSUE THREAD

**Issue by jacobtruman** [KnpLabs/php-github-api#637]
There does not seem to be the ability to access the pagination of search results.

**Comment by acrobat** [comment]
Can you provide some code which does not work as expected? This makes it a bit easier to replicate and test the buggy behavior. Thanks!

**Comment by jacobtruman** [comment]
For example, from the documentation, searching code for a string:

$files = $client->api('search')->code('@todo language:php');

This will return an array with three sub arrays; one is items and another is a total number of items found. By default, the number of items returned is 30. If the total number of items found is more than 30, there is no way to get the rest of them.

**Comment by jacobtruman** [comment]
The pull request class supports this:

https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/PullRequest.php#L61-L69

**Comment by justinriddiough** [comment]
I'm experiencing this with             
$githubClient->api('user')->subscriptions('username');

**Comment by acrobat** [comment]
I've tested both the search api and user subscriptions api and they correctly seem to paginate. So I'm closing this issue for now. If anyone is still experiencing problems, please open a new issue!
