### ISSUE TITLE
API for  getting repository topics?

### ISSUE THREAD

**Issue by mkoske** [KnpLabs/php-github-api#638]
Is it possible to get all repository [topics](https://developer.github.com/v3/repos/#list-all-topics-for-a-repository)?

**Comment by m1guelpf** [comment]
@mkoske I think the only possible way to do this is using GraphQL...

**Comment by acrobat** [comment]
Github has an api endpoint for this but it's still in preview mode. See https://developer.github.com/v3/repos/#list-all-topics-for-a-repository

We don't currently have support for this endpoint but feel free to submit a PR for this! Or you can call that endpoint manually [like this](https://github.com/KnpLabs/php-github-api/blob/13003af4d8f5abf8e55a8ad38a4eea4dfed5a513/doc/request_any_route.md)

**Comment by acrobat** [comment]
Fixed in #657
