### ISSUE TITLE
Commit / push

### ISSUE THREAD

**Issue by AdamMiltonBarker** [KnpLabs/php-github-api#652]
Hi guys cannot seem to find the docs for committing and pushing, could you share the link please.

**Comment by acrobat** [comment]
@AdamMiltonBarker can you provide a link to the github api docs for the missing feature?

**Comment by AdamMiltonBarker** [comment]
Yep, going off the following article, the first link is required also:

http://patrick-mckinley.com/tech/github-api-commit.html

https://developer.github.com/v3/repos/commits/
https://developer.github.com/v3/git/commits/

Was just wondering if it was already in place.

**Comment by acrobat** [comment]
As far as I can see we have support for these endpoints:

- Repo commits:
  - Code: https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/Repository/Commits.php
  - Docs: https://github.com/KnpLabs/php-github-api/blob/master/doc/commits.md
- Gitdata commtis:
  - Code: https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/GitData/Commits.php
  - Docs: https://github.com/KnpLabs/php-github-api/blob/master/doc/gitdata/commits.md

**Comment by AdamMiltonBarker** [comment]
Cool will check it out, thanks.

**Comment by AdamMiltonBarker** [comment]
Hi @acrobat  regarding this, which functionality allows us to get the reference of the last commit per the docs:

https://developer.github.com/v3/repos/commits/#get-the-sha-1-of-a-commit-reference

**Comment by AdamMiltonBarker** [comment]
Also there does not appear to be functionality for trees:

https://developer.github.com/v3/git/trees/

**Comment by AdamMiltonBarker** [comment]
Hi @acrobat any suggestions on where I could find these features, have checked through and am unable to find.

**Comment by acrobat** [comment]
Git tree:
Code: https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/GitData/Trees.php
Docs: https://github.com/KnpLabs/php-github-api/blob/master/doc/gitdata/trees.md

For the get sha I've have to look, I couldn't find one for now, but it could be a missing feature

**Comment by AdamMiltonBarker** [comment]
OK thanks for the help, would it be possible to reopen this until its found ?
