### ISSUE TITLE
Prepare a new minor release. 

### ISSUE THREAD

**Issue by Nyholm** [KnpLabs/php-github-api#662]
We should prepare a change log and create a new release

**Comment by acrobat** [comment]
I will try to do one today/tomorrow!

**Comment by Nyholm** [comment]
Awesome. I'll do some review as well. Probably tonight

**Comment by Nyholm** [comment]
I'll start with this now

**Comment by acrobat** [comment]
Ok thanks, I didn't have the time yet do start on it

**Comment by acrobat** [comment]
[2.7.0 was released](https://github.com/KnpLabs/php-github-api/releases/tag/2.7.0)
