### ISSUE TITLE
Unable to use with PHP5.6

### ISSUE THREAD

**Issue by manuelgrabowski** [KnpLabs/php-github-api#670]
Hi there, php-http/guzzle6-adapter is required in 1.1, which is pulling in symfony/options-resolver v4.0.2 which already requires PHP7.1+ – hopefully I'm doing something wrong, but to me it seems that it's currently not possible to use this library with anything below PHP7.1. (We're trying with 5.6.30 right now.)

**Comment by acrobat** [comment]
Can you provide the composer file you are using.

**Comment by GrahamCampbell** [comment]
It only pulls in that if you are using php 7.1, otherwise it'll pull in an older version so that it works.

**Comment by manuelgrabowski** [comment]
Thanks for the quick replies, I see what the problem is… I was using PHP7 locally and pushing to production where there's still version 5.6.30. I figured I could mitigate this by specifying it in my `composer.json` before executing the require command.

This is my composer.json:
```
{
    "require": {
    },
    "config": {
        "platform": {
            "php": "5.6.30"
        }
    }
}
```

This is the error I'm getting:
```
$> php composer.phar require knplabs/github-api php-http/guzzle6-adapter
Using version ^2.7 for knplabs/github-api
Using version ^1.1 for php-http/guzzle6-adapter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/options-resolver v4.0.2 requires php ^7.1.3 -> your PHP version (7.1.7) overridden by "config.platform.php" version (5.6.30) does not satisfy that requirement.
    - symfony/options-resolver v4.0.2 requires php ^7.1.3 -> your PHP version (7.1.7) overridden by "config.platform.php" version (5.6.30) does not satisfy that requirement.
    - symfony/options-resolver v4.0.2 requires php ^7.1.3 -> your PHP version (7.1.7) overridden by "config.platform.php" version (5.6.30) does not satisfy that requirement.
    - Installation request for symfony/options-resolver (locked at v4.0.2) -> satisfiable by symfony/options-resolver[v4.0.2].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by xabbuh** [comment]
Your issue seems to be that the OptionsResolver component is already installed in a version that does not work with PHP 5. You should update your existing dependencies first to be compatible with PHP 5.6 before adding new.

**Comment by manuelgrabowski** [comment]
Wow, you are fast. I deleted my composer.lock and./vendor folder, and indeed the require-command ran fine. I just deployed that to production and it works like a charm! Thanks a lot for providing me with basic steps for composer unrelated to the actual project, and sorry for the incorrect issue!

**Comment by Kyslik** [comment]
@manuelgrabowski also take a look at the chart at the bottom of [php/supported-versions](http://php.net/supported-versions.php) page
