### ISSUE TITLE
Closed Pull Requests pagination

### ISSUE THREAD

**Issue by acidaniel** [KnpLabs/php-github-api#674]
Hi, Im trying to have a list of closed Pull requests, if I implement something like:

```php
  /**
   * Get Closed Pull Requests.
   */
  public function getClosedPullRequests($repository) {
    $closedPulls = $this->getGithubClient()->api('pull_request')
     ->all(self::ORGANIZATION, $repository, ['state' => 'closed']);

  }
```
I will have results limited to 30 results. I'm trying to implement pagination with no luck.

I've tried several ways, but seems nothing in the documentation helps. Could you point me to the right direction?

what I've tried is something like:

```php
  /**
   * Get Closed Pull Requests.
   */
  public function getClosedPullRequests($repository) {
    $repoApi = $this->getGithubClient()->api('pull_request');
    $paginator = new ResultPager($this->githubClient);
    $parameters = [self::ORGANIZATION, $repository, ['state' => 'closed']];
    $prs = $paginator->fetch( //Also I've tried here with fetchAll
      $repoApi,
      'repositories', // I've tried here with pulls, issues, repositories and nothing seems to work
      $parameters
    );
  }
```
I did something similar for the contributors and that one works good.

```php
public function getAllContributors($repository) {
    $repoApi = $this->getGithubClient()->api('repo');
    $paginator = new ResultPager($this->githubClient);
    $parameters = [self::ORGANIZATION, $repository];
    $contributors = $paginator->fetchAll(
      $repoApi,
      'contributors',
      $parameters
    );

    return $contributors;
  }
```
Thanks

**Comment by svenluijten** [comment]
Unsure at the moment, but it looks like this is an issue on GitHub's side. I've noticed some endpoint _not_ actually returning a `Link` header, preventing this package from getting the `next` and `previous` URLs to fetch for pagination.

For instance, this is also happening on `/user/repos`. I've [contacted GitHub about this](https://twitter.com/svenluijten/status/979781867296747520).

**Comment by acrobat** [comment]
Keep us updated @svenluijten!

**Comment by ElijahLynn** [comment]
I am digging in now to an issue we are seeing with a PR not being in the all() results. A manual `curl` says it is in a "Link" that is page 2. I'll post my findings shortly.

**Comment by acrobat** [comment]
I've tested the `PullRequest::all` endpoint with the result pager and all seems to work well

```php
$client = new \Github\Client();
$paginator  = new Github\ResultPager($client);

$result = $paginator->fetchAll($client->pullRequest(), 'all', ['KnpLabs', 'php-github-api', ['state' => 'closed']]);

var_dump(count($result));
// int(624)
var_dump($paginator->getPagination());
/*
array(2) {
  'prev' =>
  string(82) "https://api.github.com/repositories/3948501/pulls?state=closed&per_page=100&page=6"
  'first' =>
  string(82) "https://api.github.com/repositories/3948501/pulls?state=closed&per_page=100&page=1"
}
*/
```

If anyone is still experiencing problems, please open a new issue!
