### ISSUE TITLE
Events: limitation of per page

### ISSUE THREAD

**Issue by dereuromark** [KnpLabs/php-github-api#675]
You added
```
public function events($username, $repository, $page = 1)
```
But this way you cannot set a "per page" config.

Instead this should be done IMO:
```
    /**
     * @param string $username
     * @param string $repository
     * @param array $params
     *
     * @return array
     */
    public function events($username, $repository, array $params = [])
    {
        $url = 'repos/' . rawurlencode($username) . '/' . rawurlencode($repository) . '/events';

        $params = [
            'per_page' => 50,
        ] + $params;

        return $this->get($url, $params);
    }
```

That overcomes the default limit of 30 which is currently hardcoded in your code (unless I overlooked something).

**Comment by carlosbuenosvinos** [comment]
Hi @dereuromark! Thanks for the opening this issue. Here are my comments:

30 events is a hardcore value because GitHub defines it like this in its documentation. You can take a look at: https://developer.github.com/v3/activity/events/

> Events support pagination, however the per_page option is unsupported. The fixed page size is 30 items. Fetching up to ten pages is supported, for a total of 300 events.

So, IMHO I think this is not an issue. Maybe it could be improved in the inline documentation.

**Comment by dereuromark** [comment]
They are setting a **default**. My point was to add a way to allow changing the default.
So yeah, this is an issue.
An additional param could work, or using an array config.
See my provided example above.

Up to 200 is possible, if you read their API.

**Comment by ssb402** [comment]
What's the reason behind not supporting `per_page` for this API? I'm curious, and would like to learn the rationale behind this decision.

**Comment by GrahamCampbell** [comment]
Use the result pagert class.

**Comment by acrobat** [comment]
Closing this issue as @GrahamCampbell indicated that you should use the [`ResultPager`](https://github.com/KnpLabs/php-github-api/blob/5c540ae71ae175e9763d8cabbea48fea387718b7/doc/result_pager.md) for this.
