### ISSUE TITLE
How to use pagination with Gists?

### ISSUE THREAD

**Issue by A973C** [KnpLabs/php-github-api#68]
Hi!

Sorry if my question is stupid but I don't understand how to use pagination with a specific user Gists list.

Could you please provide me a full working example?

Thank you so much!

**Comment by Spreeuw** [comment]
For anyone with the same question, the answer is you should call `all` in the `$paginator`, not `gists` as in the OP:
```php
$client     = new Github\Client();
$gists      = $client->api('gists');
$per_page   = 5;
$paginator  = new Github\ResultPager($client, $per_page);

// first page
$result     = $paginator->fetch($gists, 'all');

// next page
$result     = $paginator->fetchNext();
```
