### ISSUE TITLE
Obscure API Connection Support

### ISSUE THREAD

**Issue by Moon-Hub** [KnpLabs/php-github-api#682]
Hear me out, the app i'm building needs a connection to a more "obscure" api string - which i've easily done with just a regular curl request.

However, does this library support such things? For example searching for code
`$code = $client->api('search')->code('exec language:php');` then making each item in the array `= $item` Now, inside each $item is `$item['text_matches'][$i]['object_url'];` 

`['object_url]` will look something like this `https://api.github.com/repositories/86386555/contents//gabok.php?ref=e0d0678c425c2f8dc8177d1b5ee5079c89b10358` Which gives me access to the `RAW` file that i need to loop through.

So, is this possible with the library, or will i have to stick to my original curl request?

Also, on second thought - is there any  documentation i can look at that shows me how i can increase the `CURLOPT_CONNECTTIMEOUT` and `CURLOPT_TIMEOUT` I cant seem to find it...

**Comment by acrobat** [comment]
@Moon-Hub I think you can do that with this part of the docs: https://github.com/KnpLabs/php-github-api/blob/f17c158af84f9b3c7279e5ca9dc4329d69e6d3ed/doc/request_any_route.md
