### ISSUE TITLE
Repo API Broken in master

### ISSUE THREAD

**Issue by GrahamCampbell** [KnpLabs/php-github-api#685]
`$paginator->fetchAll($client->me(), 'repositories', ['all'])` will throw:

`Github\Exception\RuntimeException`: If you specify visibility or affiliation, you cannot specify type.

**Comment by GrahamCampbell** [comment]
This must have been broken somewhere between: https://github.com/KnpLabs/php-github-api/compare/2.7.0...b716e03f9cd6d259599891806a210290eecd565a.

**Comment by acrobat** [comment]
Hmm good catch. We can fix this by making the default value of the new parameters `null` and add some extra code in the method to unset the `type` value if visibility or affiliation is set?

What do you think @GrahamCampbell @hotmeteor?
