### ISSUE TITLE
List all pr

### ISSUE THREAD

**Issue by Mariusz08** [KnpLabs/php-github-api#690]
How do I list all pull requests using api? Thanks.

**Comment by Nyholm** [comment]
Hey. 
Not sure, what does the documentation say?

**Comment by Mariusz08** [comment]
Sure. And how do I check id of pr?

**Comment by Nyholm** [comment]
It seams like you prefer me telling you then actually read the documentation yourself.

**Comment by acrobat** [comment]
Hi @Mariusz08,

In the GitHub repository we only discuss bugs and new features. For this kind of questions please dig into the docs of this library or the official github api docs. Here are some links to get you started!

[Php github api - list all pullrequests](https://github.com/KnpLabs/php-github-api/blob/master/doc/pull_requests.md#list-all-pull-requests-per-repository) and [Official github api docs](https://developer.github.com/v3/pulls/#list-pull-requests).

Thanks!
