### ISSUE TITLE
Reviews method error

### ISSUE THREAD

**Issue by Mariusz08** [KnpLabs/php-github-api#691]
When I use method reviews(), php print error: "Uncaught Error: Call to undefined method Github\Api\PullRequest::reviews() in...". How do I fix it? Thanks.

**Comment by acrobat** [comment]
@Mariusz08 Please check the documentation about the [pullrequest reviews api](https://github.com/KnpLabs/php-github-api/blob/master/doc/pull_request/reviews.md). The methods of the api classes are not static so you can't call them like `Github\Api\PullRequest::reviews()`
