### ISSUE TITLE
Search API Pagination ignoring parameters

### ISSUE THREAD

**Issue by dafow** [KnpLabs/php-github-api#705]
This one is concerning the Search API, in which the `per_page`and `page`parameters are ignored when used with the ResultPager:

```php
$search_api = $github_client->api( 'search' );
$paginator = new Github\ResultPager( $github_client );
$repos = $paginator->fetch( $search_api, 'repositories', array(
  'q'  =>  $query,
  'per_page'  =>  5,
  'page'  =>  2
) );
```

Always returns 30 items of the 1st page. Am I misusing the API ?
I do notice that the Search API `repositories`function consists of
```php
public function repositories($q, $sort = 'updated', $order = 'desc')
{
  return $this->get('/search/repositories', ['q' => $q, 'sort' => $sort, 'order' => $order]);
}
```
so it might makes sense that it doesn't work. Is it actually an issue or are users expected to call the ResultPager with the default 30 items per page and call `fetchNext`manually ?

**Comment by acrobat** [comment]
With the result pager you have 2 options, see the [ResultPager](https://github.com/KnpLabs/php-github-api/blob/master/doc/result_pager.md) for more info. In your example you are passing the page and per_page parameters to the api method, but these will be overwritten by the result pager as you should "control" these parameters through the result pager itself.

Using `fetch` and looping over all pages until the last page is reached.
```php
$paginator = new Github\ResultPager($client, /* Optional items per page parameter */);
$result = $paginator->fetch($client->pullRequest(), 'all', ['KnpLabs', 'php-github-api', ['state' => 'closed']]);
while ($paginator->hasNext()) {
    $result = $paginator->fetchNext();
}
```

Using fetchAll to retrieve all rows at once.
```php
$paginator = new Github\ResultPager($client);
$result = $paginator->fetchAll($client->pullRequest(), 'all', ['KnpLabs', 'php-github-api', ['state' => 'closed']]);
```
