### ISSUE TITLE
Giving a custom git URL (organizational URL)

### ISSUE THREAD

**Issue by rishiraaz** [KnpLabs/php-github-api#706]
Is there any way I can define  custom git url, needed as org url is different.

**Comment by robbieaverill** [comment]
What do you mean exactly? I've used this repository quite recently for organisation based repositories, and the documentation also provides examples which are organisation based.

**Comment by acrobat** [comment]
I'm closing this issue as no further feedback has been provided. Please reopen this issue or leave a comment if you can provide more information.
