### ISSUE TITLE
download a file which is symlinked

### ISSUE THREAD

**Issue by TiMESPLiNTER** [KnpLabs/php-github-api#707]
Is it somehow possible to download a file to which a symlink points to?

When I try to download it, I get the following exception:

> Path "symlinkedFile.yml" is not a file.

Which is basically true. But I couldn't find any method within this lib which could resolve me the symlink to the real path.

**Comment by acrobat** [comment]
This doesn't seem to be an issue for the github api: https://developer.github.com/v3/repos/contents/#response-if-content-is-a-symlink

Can you provide some example code (and maybe a test repo with a symlink) so we can check if the library has a bug in this behavior or not?

**Comment by TiMESPLiNTER** [comment]
@acrobat  The problem is in this line of code:

https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/Repository/Contents.php#L279

as `type` has the value `symlink` in the case of a symlink and not `file`. I'll do PR.

**Comment by acrobat** [comment]
Ok, thanks @TiMESPLiNTER! Please let us know if you need help with the PR.

**Comment by acrobat** [comment]
@TiMESPLiNTER I've provided a fix in #751. Can you test if this solves your problem? Thanks!
