### ISSUE TITLE
Subfolders & Files doesn't update

### ISSUE THREAD

**Issue by BenjaminHoegh** [KnpLabs/php-github-api#709]
When trying to look into a folder there contain a subfolder and a file, only the file are showed. 

#### Example at GitHub:

- readme.md
- folder
  - test.md
  - subfolder
    - test2.md

#### API result

- readme.md
- folder
  - test.md

I then tried to create some files too, also in the root, they are vanished too.

this also happens when using the URL e.g api.github.com/repos/KnpLabs/php-github-api/git/trees/aa1deb050c4e8c3c180bc934c1a5ca47c216dffd in the browser

Is there a delay from when it has been created until the API can see it? or is there a bug in the code? or is it GitHub there has an issue?

**Comment by acrobat** [comment]
Can you provide some example code and repository to check against? The library itself won't delay the display of changes, unless you cache the result. Maybe you can contact github support to ask about this specific case

**Comment by acrobat** [comment]
I'm going to close this issue for now as it looks like it's no issue of the php lib but more of caching/delay on github's side. Maybe you can request some more info through github support.

If this would be related to this library, please leave a comment so we can reopen the issue!
