### ISSUE TITLE
Search inside repository

### ISSUE THREAD

**Issue by ClicShopping** [KnpLabs/php-github-api#715]
It's not an issue but I could be interesting to make an example how search inside a repository
for example you have a repositori call AddOnsMyApplication, inside you have a direcory callled analytics, another called products
AddOnsMyApplication
    --- analytics
    ---- products

To have information about AddOnsMyApplication, is t'ok
$client->api('repo')->find('AddOnsMyApplication');

but to search information by a keyworks inside AddOnsMyApplication, I don't see how to make that. For example inside AddOnsMyApplication I research "%an%" to have all the addons with An.

Thank you

**Comment by acrobat** [comment]
I'm closing this for now, feel free to open a PR with some extra docs examples.
