### ISSUE TITLE
How can I find the number of lines changed for a commit?

### ISSUE THREAD

**Issue by bret-2600** [KnpLabs/php-github-api#717]
Is there a way to find the number of lines changed for a commit for a particular project?  Thanks!

**Comment by bret-2600** [comment]
Nevermind!  I figured it out.  I had to retrieve the individual commits using code such as $commit = $client->api('repo')->commits()->show([organization], [repo], $sha);

**Comment by Nyholm** [comment]
Thank you for coming back with the answer.
