### ISSUE TITLE
Heads up: Stricter validation coming soon on add issue assignee endpoint

### ISSUE THREAD

**Issue by kytrinyx** [KnpLabs/php-github-api#737]
Hi 👋 ,

I an engineer on the API team at GitHub. A colleague and I are currently going through GitHub's REST API, tightening up validations.

We noticed that a fair number of requests from this library to the [Add issue assignee](https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue) endpoint that are passing a single assignee as a string, rather than as an array with one string in it.

While the code seems to be handling this on the backend, the documentation specifies an array of strings, and we're going to get stricter about that, and start validating that the payload is, in fact, an array of strings.

That means that you'll be getting [422 Unprocessable Entity](https://httpstatuses.com/422) back from this API as soon as we flip the switch.

We're expecting to make this change in about a week, and wanted to give you a heads up so you're not caught by surprise.

**Comment by Nyholm** [comment]
Excellent. Thank you. 

Is anyone willing to do a PR? We should be quick with the review, merge and release.

**Comment by acrobat** [comment]
Hi @kytrinyx, 

Thanks for the heads up! Like @Nyholm already said, if some provides a PR we can have it released fairly quick. Otherwise I will try to look into fixing this.

**Comment by acrobat** [comment]
I've provided a PR to convert the parameter to an array if the user didn't do it. See #738 

@Nyholm we can remove this conversion and implement an exception when we fix issue #566

**Comment by acrobat** [comment]
A fix is released in [2.10.1](https://github.com/KnpLabs/php-github-api/releases/tag/2.10.1)

**Comment by Nyholm** [comment]
You are the best. Thank you for your work!
