### ISSUE TITLE
Building a ui for this repo

### ISSUE THREAD

**Issue by husseinmirzaki** [KnpLabs/php-github-api#742]
Is it a good idea to build a ui for this library? 
[here is the repo](https://github.com/husseinmirzaki/hosting-git-helper)

**Comment by robbieaverill** [comment]
Wow, that's pretty cool @husseinmirzaki! 

I think things like that should stay decoupled though, the majority of people using this library would be as an SDK and wouldn't want/need a UI for it probably.

**Comment by husseinmirzaki** [comment]
aha thanks
