### ISSUE TITLE
Get Archive link

### ISSUE THREAD

**Issue by husseinmirzaki** [KnpLabs/php-github-api#743]
How can we avoid the server from downloading and make the user download the requested archive ?
Don't we need a link ? But what we get is the content of the archive right ?
What i mean is how to avoid following the header "Location" ?
I can add a `nofolow` variable to the `__construct` and avoid adding no follow plugin then I could manually call the api and get link the from `Location` header but i think that would be wrong.
is there any other way to do this ?

**Comment by husseinmirzaki** [comment]
Sorry, Its solved

**Comment by baohx2000** [comment]
@husseinmirzaki  How did you solve this?
