### ISSUE TITLE
has_project missing

### ISSUE THREAD

**Issue by dereuromark** [KnpLabs/php-github-api#746]
https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/Repo.php#L193
```php
public function create(
        $name,
        $description = '',
        $homepage = '',
        $public = true,
        $organization = null,
        $hasIssues = false,
        $hasWiki = false,
        $hasDownloads = false,
        $teamId = null,
        $autoInit = false
    ) {
```
is missing the documented `has_projects`, which unfortunately defaults to true (we need false)

See https://developer.github.com/v3/repos/#create

PS: best to not add so many arguments in the first place. It is cleaner to use an attributes array :)
Also for order here not to matter. Currently, it is painful to only overwrite the last one.

**Comment by acrobat** [comment]
I've created a pr #752 to add the missing parameter. You're indeed right that it's not good how the current method signature looks but I've kept it for now. We will do a refactor when we start working on v3 (as this kind of change will also be applied to other parts of the code)
