### ISSUE TITLE
Merge and Fork list features in library

### ISSUE THREAD

**Issue by davemg3** [KnpLabs/php-github-api#748]
Hello,
I want to use your lib to build some statistics on some repositories but 
The fork list feature while present in https://developer.github.com/v3/repos/forks/ but doesnt see to be in library.
Is it a feature needed to be implemented?

(also Can you confirm how to call next page with lib when doing `$this->github->repo()->commits()->all('GrahamCampbell','Laravel-GitHub',[])`;
as I only manage to get first 30 results)

Thk u

**Comment by acrobat** [comment]
There is already support available for the repository forks api in [repo/forks](https://github.com/KnpLabs/php-github-api/blob/e54725e08eb806011ffb22b592e1a9b60233b4f9/lib/Github/Api/Repository/Forks.php)

It's best to check the available documentation on [result pagers](https://github.com/KnpLabs/php-github-api/blob/e54725e08eb806011ffb22b592e1a9b60233b4f9/doc/result_pager.md)
