### ISSUE TITLE
contributors method doesnt have 'page' parameter

### ISSUE THREAD

**Issue by davemg3** [KnpLabs/php-github-api#750]
Hello,
In Github doc, it specified we can set a page and per_page parameter 
but function as contributors()  lacks an array parameter for this purpose, so only 1st page is returned
```
    public function contributors($username, $repository, $includingAnonymous = false)
    {
        return $this->get('/repos/'.rawurlencode($username).'/'.rawurlencode($repository).'/contributors', [
            'anon' => $includingAnonymous ?: null,
        ]);
    }
```

Same thing for methods as `user()->repositories`,  `repo()->activity()` or `repo()->frequency()`

Is there a reason not to have implemented this array argument for such methods?

**Comment by acrobat** [comment]
The [result pager](https://github.com/KnpLabs/php-github-api/blob/master/doc/result_pager.md) is actually recommended to use in these kind of cases. It will set the correct page and per_page values automatically.
