### ISSUE TITLE
"php-http/client-implementation" no matching package found

### ISSUE THREAD

**Issue by afbora** [KnpLabs/php-github-api#756]
````
"require": {
    "php": "^7.1.3",
    "knplabs/github-api": "^2.10"
}
````
I got following errors with above composer requires:

> Problem 1
    - knplabs/github-api 2.11.x-dev requires php-http/client-implementation ^1.0 -> no matching package found.
    - knplabs/github-api 2.10.1 requires php-http/client-implementation ^1.0 -> no matching package found.
    - Installation request for knplabs/github-api ^2.10.1 -> satisfiable by knplabs/github-api[2.10.1, 2.11.x-dev].

I checked `php-http/client-implementation` repository and it is not found!

**Comment by afbora** [comment]
````
"require": {
    "php": "^7.1.3",
    "knplabs/github-api": "^2.10",
    "php-http/guzzle6-adapter": "^1.1"
}
````
Working with that!

**Comment by GrahamCampbell** [comment]
Yeh, you also need install a package that "implements" `php-http/client-implementation`. It is a virtual package, like the psr log implementation virtual package. Check the install section of the readme for the details: https://github.com/KnpLabs/php-github-api#install.

**Comment by acrobat** [comment]
Yes indeed, you need to require a specific implementation (driver). [Here is a list of the available adapters](https://packagist.org/providers/php-http/client-implementation) "implementing" the virtual package.
