### ISSUE TITLE
cURL error 77: error setting certificate verify locations: CAfile

### ISSUE THREAD

**Issue by cavo789** [KnpLabs/php-github-api#757]
Good morning all,

Using `php-github-api` first on my localhost, I was facing this error: `Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 77: error setting certificate verify locations: CAfile`.

The solution is given in the Guzzle repository: https://github.com/guzzle/guzzle/issues/1935#issuecomment-371756738

Hope this can helps someone else.
 
And thank you KNP Labs for your great library!

**Comment by Eze4Manuel** [comment]
Connections from your localhost arent not secured. Either you install openSSL in your localhost or you try working on your work remotely via a secured connection

**Comment by tiagofrancafernandes** [comment]
I found this solution: https://github.com/guzzle/guzzle/issues/1935#issuecomment-629548739

Use 'verify => false'

```php
$client = new Client([
      'base_uri'        => 'https://api.target'
      'verify'          => false, //https://github.com/guzzle/guzzle/issues/1935#issuecomment-629548739
      'headers'         => [
       //Your header here
  ]
]);
```
