### ISSUE TITLE
2.11.0 Release

### ISSUE THREAD

**Issue by GrahamCampbell** [KnpLabs/php-github-api#770]
Is a 2.11.0 tag coming soon please?

**Comment by acrobat** [comment]
@GrahamCampbell I will go throught the open pr's and try to make a new release today/tomorrow!

**Comment by acrobat** [comment]
@GrahamCampbell I've pushed a new release! See https://github.com/KnpLabs/php-github-api/releases/tag/2.11.0

**Comment by GrahamCampbell** [comment]
Perfect. :)
