### ISSUE TITLE
A common interface for interacting with Git providers (RFC)

### ISSUE THREAD

**Issue by m1guelpf** [KnpLabs/php-github-api#772]
In case you don't know me, I'm a maintainer of the most popular [PHP GitLab API client](https://github.com/m4tthumphrey/php-gitlab-api). I've also contributed a few times to this repo and built some apps that use this library.

Right now, all this, Gitlab's and BitBucket's PHP clients have the same structure (using HTTPug) and, while all platforms have their own set of functionalities, most of them are shared between platforms (repos, users, PR/MR, etc.).

Also, if you've ever built an app using this library, you'll probably have noticed how users of other providers start asking for support almost immediately.

So, inspired by the Flysystem PHP library, I'd like to propose the development of a shared interface that allows someone to interact with the most popular Git providers just by swapping drivers.

I believe this would reduce the amount of code you have to write on new projects (I have like three simple implementations of this in different projects, and I'm sure others do as well) and prevent market domination by GitHub (as it seems to be, by far, the one with most integrations out there).

Would love to know what everyone thinks about this!

cc'ing @GrahamCampbell as StyleCI now supports all three providers, and @Nyholm as he's the one that has interacted with me the most on my PRs

**Comment by GrahamCampbell** [comment]
All the APIs are kinda different tbh.

**Comment by GrahamCampbell** [comment]
The domain objects don't even match up. For example, in GitLab, projects belong to users or groups, and then repos belong to projects. GitHub and Bitbucket have no concept of projects, only repos, users, and teams/organizations.

The API for merging a PR is quite different, and that for commit status. Listing the users repos is very different too. In GitLab and GitHub, you can ask for a list of repos the user is a collaborator on. In Bitbucket you cannot. You have to make multiple API requests,

**Comment by acrobat** [comment]
I would be a cool idea indeed but I think it would be possible at all as the api's of github, gitlab and bitbucket are quite different. So it would be really hard to define a common interface and still support all features of each api.

Thanks for the idea @m1guelpf but I'm closing this issue as it is not really possible imo. If anyone has different idea's of this or more info feel free to leave a comment! We can still re-open the issue afterwards.
