### ISSUE TITLE
Describe request\response models as objects

### ISSUE THREAD

**Issue by makasim** [KnpLabs/php-github-api#773]
Right now, the API methods send and return plain arrays. 

This approach is simple but has some disadvantages:

* Hard to tell what fields an array  might have
* There is no autocomplete for available methods and properties. 
* Could not be used as a type hint in user code. 

I propose to introduce such models as array wrappers. [formapro/telegram-bot](https://github.com/formapro/telegram-bot-php)  is an example of such approach.

I could work on such addition. Would you be interested in such an addition?

* There is no serialization\deserialization logic
* It comes with no performance cost. 
* Easy to use
* Explicit API

**Comment by OskarStark** [comment]
cc @Soulivaneuh

**Comment by makasim** [comment]
more in PR https://github.com/KnpLabs/php-github-api/pull/774
