### ISSUE TITLE
Get Archive Link

### ISSUE THREAD

**Issue by sidedwards** [KnpLabs/php-github-api#776]
# Issue getting archive link
Is [`contents()->archive()`](https://github.com/KnpLabs/php-github-api/blob/master/doc/repo/contents.md#get-repository-archive) not a wrapper for [Get Archive Link](https://developer.github.com/v3/repos/contents/#get-archive-link)?

Reference to: https://github.com/KnpLabs/php-github-api/issues/743

## Code
```
require_once __DIR__ . '/../vendor/autoload.php';

$client = new \Github\Client();
$client->authenticate([AUTH_TOKEN], Github\Client::AUTH_URL_TOKEN);
$archive = $client->api('repo')->contents()->archive([AUTHOR], [REPO], 'zipball');

var_dump($archive);
```

## Response
It looks like I'm getting a serialized response of the actual file vs a link w/ token

![screen shot 2019-02-04 at 5 59 05 pm](https://user-images.githubusercontent.com/11489608/52247308-a9cd5880-28a6-11e9-9e87-068203848586.png)

**Comment by acrobat** [comment]
@sidedwards As it seems from the method docblock the `archive` method will return the repository archive binary data. So you should be able to write this output to a file to retrieve the zipball.

https://github.com/KnpLabs/php-github-api/blob/e6a499758c994804a2cd019eb5976e2bbabca8ec/lib/Github/Api/Repository/Contents.php#L240-L260

The example on the github api docs also shows the case to call the api and pipe the result into a file. https://developer.github.com/v3/repos/contents/#get-archive-link
