### ISSUE TITLE
Not Found error when creating issue

### ISSUE THREAD

**Issue by gearoidc** [KnpLabs/php-github-api#778]
I am getting a Not Found error when trying to create an issue on a Public repo I have using credentials from oAUTH app I have setup and also an application I created. I can list the repo and query issues, just not create them.

```
<?php
require_once __DIR__ . '/vendor/autoload.php';
$client = new \Github\Client();
$repositories = $client->api('user')->repositories('gearoidc');
$client->authenticate('aaaaaaaa', 'bbbbbbbbbbbbbbb', Github\Client::AUTH_URL_CLIENT_ID);
// This call fails
$info = $client->api('issue')->create('gearoidc', 'testing', array('title' => 'The issue title', 'body' => 'The issue body')); 
// This will work
$issues = $client->api('issue')->all('gearoidc', 'testing', array('state' => 'open'));
```

I am however able to create issues using a Personal Access Token using beefed up admin privileges. 
```
<?php
require_once __DIR__ . '/vendor/autoload.php';
$client = new \Github\Client();
$repositories = $client->api('user')->repositories('gearoidc');
$client->authenticate('patpatpatpatpat', Github\Client::AUTH_HTTP_TOKEN);
$info = $client->api('issue')->create('gearoidc', 'testing', array('title' => 'The issue title', 'body' => 'The issue body'));
print_r($info);
$issues = $client->api('issue')->all('gearoidc', 'testing', array('state' => 'open'));
print_r($issues);
```

Reckon I am not setting some access level or something or other ....

Thanks in advance

**Comment by acrobat** [comment]
Does the oAuth app ask for `repo` permissions? I'm closing this issue as it's not related to this lib itself, so maybe you can contact github support or ask your question on the [github community](https://github.community/) forums.
