### ISSUE TITLE
PhP sticky forms 

### ISSUE THREAD

**Issue by Avneetkaurr** [KnpLabs/php-github-api#783]
I am trying to make a code using the sticky forms with php. can someone help me what I am doing wrong since my code is not working properly. 

<!DOCTYPE html PUBLIC "-//W3C//DTD SHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1-transitional.dtd">
<html xmls="http://www.w3.org/1999/xhtml">
<head>
	<meta charset="utf-8">
	<title>The Coffee House</title>
	<style type="text/css" media="screen"> .error { color:red; }
	</style>
</head>

File: display_user_info
Description: 
 
/* This script receives values from coffee.html:
coffee, type, quantity, name, email, telephone, address. city, state, zip */

Author: Avneet Kaur
Date: February 25, 2019
!-->

<body>
<!-- Script 6.3 display_user_info.php --!>

<h1>The Coffee House</h1>
<h3>Order Summary</h3>
<?php 

// Address error management, if you want
//Coffee Names Array
$CoffeeNames['Boca Villa'] = 'Boca Villa';
$CoffeeNames['South Beach Rhythm'] = 'South Beach Rhythm';
$CoffeeNames['Pumpkin Paradise'] = 'Pumpkin Paradise';
$CoffeeNames['Sumatran Sunset'] = 'Sumatran Sunset';
$CoffeeNames['Bali Batur'] = 'Bali Batur';
$CoffeeNames['Double Dark'] = 'Double Dark';

//Coffee prices array
$CoffeeCosts['Boca Villa'] = 7.99;
$CoffeeCosts['South Beach Rhythm'] = 8.99;
$CoffeeCosts['Pumpkin Paradise'] = 8.99;
$CoffeeCosts['Sumatran Sunset'] = 9.99;
$CoffeeCosts['Bali Batur'] = 10.95;
$CoffeeCosts['Double Dark'] = 9.95;
//Validate the values:
$problem = false;
	if (isset($_POST['submit'])) {
		
			$errors = "<p>The following errors were found:</p>";
		if(empty($_POST['coffee'])) {
		$problem = true;
		$errors .= "<label class = 'error'> Please choose the Coffee</label><br/>";
		}	
	if(empty($_POST['type'])) {
		$problem = true;
		$errors .= "<label class = 'error'> Please Select the coffee type</label><br/>";
	}
		if(empty($_POST['quantity'])) {
		$problem = true;
		$errors .= "<label class = 'error'> Please enter the Quantity</label><br/>";
	}
		if(empty($_POST['name'])) {
		$problem = true;
		$errors .= "<label class = 'error'> Please enter your name</label><br/>";
	}
		if(empty($_POST['email'])) {
		$problem = true;
		$errors .= "<label class = 'error'> Please enter your E-mail Address</label><br/>";
	}
		if(empty($_POST['phone'])) {
		$problem = true;
		$errors .= "<label class = 'error'> Please enter your Phone Number</label><br/>";
	}
		if(empty($_POST['address'])) {
		$problem = true;
		$errors .= "<label class = 'error'> Please enter your address</label><br/>";
	}
		if(empty($_POST['city'])) {
		$problem = true;
		$errors .= "<label class = 'error'> Please enter your city</label><br/>";
	}
		if(empty($_POST['state'])) {
		$problem = true;
		$errors .= "<label class = 'error'> Please enter your state</label><br/>";
	}
		if(empty($_POST['zip'])) {
		$problem = true;
		$errors .= "<label class = 'error'> Please enter your zip code</label><br/>";
	}
	
	// if $problem is not equal to false
	if(!$problem) {
		//when there isn't a error
	} else {
			// if there is an error 
			print $errors;
	}
}

?>
<form action="display_user_info.php" method = "post">
	
			<p>
			<label for="Name">Quantity:</label>
			<input type="text" name="Name" size="3" title="Please enter the quantity./">
		</p>
		<p>
			<label for="Name">Name:</label>
			<input type="text" name="Name" size="20" title="Please enter your name./">
		</p>
		<p>
			<label for="Name">E-mail:</label>
			<input type="text" name="Name" size="20" title="Please enter your email address./">
		</p>
		<p>
			<label for="Name">Address:</label>
			<input type="text" name="Name" size="20" title="Please enter your address./">
		</p>
		<p>
			<label for="Name">City:</label>
			<input type="text" name="Name" size="20" title="Please enter your city./">
		</p>
		<p>
			<label for="Name">State:</label>
			<input type="text" name="Name" size="20" title="Please enter your state./">
		</p>
		<p>
			<label for="Name">Zip Code:</label>
			<input type="text" name="Name" size="20" title="Please enter your zip./">
		</p>
<a href="coffee.html">Return to order form</a>
</body>
</html>
[Coffee.docx](https://github.com/KnpLabs/php-github-api/files/3027343/Coffee.docx)
[Sticky_Online_Coffee_Store.pdf](https://github.com/KnpLabs/php-github-api/files/3027344/Sticky_Online_Coffee_Store.pdf)

**Comment by acrobat** [comment]
This issue doesn't seem to be related to this library. I suggest asking you question on stackoverflow or the [github community forums](https://github.community/) if it is related to the github api.
