### ISSUE TITLE
Issues (Labels) API doesn't support updating a label description

### ISSUE THREAD

**Issue by pqt** [KnpLabs/php-github-api#785]
It only passes through the name and color even though adding a new label has support for descriptions (with the right header)

**Comment by adam-eclabs** [comment]
This is also not working when fetching all labels
Description is missing on all requests even after setting the header and body type

`$this->github->issues()->configure('full')->labels()->all($username, $repository)`

Anyone experience this problem or can make any suggestion on a workaround for this issue?
