### ISSUE TITLE
Wrong method call 

### ISSUE THREAD

**Issue by sordev** [KnpLabs/php-github-api#789]
$client->user() and $client->users() calls $api = new Api\User($this);
when 
$client->me(),current_user(),currentUser() calls $api = new Api\CurrentUser($this);

Api\User->keys() requires user name and returns array can't create keys
 Api\CurrentUser->keys() won't need username and return Object will be able to create keys

File: https://github.com/KnpLabs/php-github-api/blob/master/doc/currentuser/publickeys.md 
Too small to request pull.

**Comment by acrobat** [comment]
Thanks for reporting the docs issue @sordev. If you have the time, please send a PR to correct this docs issue.
