### ISSUE TITLE
Upload a folder/file

### ISSUE THREAD

**Issue by christiancozzolino** [KnpLabs/php-github-api#790]
Hi, how can I upload 
1) a folder
2) a file

to my GitHub account, using the API? 
Please, can you show me the code for 1) and 2)?
Thanks in advance :)

**Comment by acrobat** [comment]
Hi @christiancozzolino,

The [https://developer.github.com/v3/repos/contents/#create-a-file](https://developer.github.com/v3/repos/contents/#create-a-file) endpoint will let you upload/create files through the github api.

https://github.com/KnpLabs/php-github-api/blob/8c26dc85f732cc6b426bd85af4cf18bdfcdb20ff/lib/Github/Api/Repository/Contents.php#L100-L121

The actual implementation you will have to write yourself, but this endpoint will get you started. Good luck!

**Comment by christiancozzolino** [comment]
Do I need Blob and Tree to accomplish my purpose? Or is the "create" function sufficient?
I don't understand what Blob and Tree are and what they are for.

My goal is to upload a project (then files and folders).
