### ISSUE TITLE
Webhook documentation

### ISSUE THREAD

**Issue by sordev** [KnpLabs/php-github-api#791]
There is actually webhook working through

Like below. But there is no documentation found.  https://github.com/KnpLabs/php-github-api/tree/master/doc

Please add full documentation for this. 

$client = self::auth($this->repo_connection);

$create_hook = $client->api('repo')->hooks()->create($repo->owner, $repo->name, $params);

$hooks = $client->api('repo')->hooks()->all($repo->owner, $repo->name);

**Comment by acrobat** [comment]
@sordev Thanks for reporting this docs issue. Please if you have the time open a PR to provide the missing documentation, we are happy to have it merged! Thanks!
