### ISSUE TITLE
Create a folder in a repository

### ISSUE THREAD

**Issue by christiancozzolino** [KnpLabs/php-github-api#793]
Hi, is it possible to create a folder in a repository?

**Comment by acrobat** [comment]
@christiancozzolino This issue tracker is used to report issues with the api. I recommend platforms like stackoverflow to get support for implementation details.

But to get you going the [create file endpoint](https://developer.github.com/v3/repos/contents/#create-a-file) is a good start. Git doesn't track empty folders so you could create a new file (.gitkeep) in the new folder you want.

**Comment by christiancozzolino** [comment]
> Git doesn't track empty folders so you could create a new file (.gitkeep) in the new folder you want.

I know how to create a file, but how can I create it in the new folder I want, if the new folder I want doesn't exist?
