### ISSUE TITLE
Usage: user create key

### ISSUE THREAD

**Issue by bastian-schur** [KnpLabs/php-github-api#794]
Hi,
i've a problem with the keys api. I want to create a ssh key for a user.

When i use this code, i get an 404 error:
```
$client = new Client();
$client->authenticate( $myToken , '' , Client::AUTH_HTTP_TOKEN );
$client->currentUser()->keys()->create( [ 'title' => '' , 'key' => 'key' ] )
```
Also the code i've found in the documentation ( https://github.com/KnpLabs/php-github-api/blob/master/doc/currentuser/publickeys.md ) doesn't work.

Anyone an idea?

**Comment by acrobat** [comment]
@bastian-schur Does the api returns a more detailed error message? As it seems to me that this call should work. See [public keys api](https://developer.github.com/v3/users/keys/#create-a-public-key)

**Comment by bastian-schur** [comment]
@acrobat No, just a 404 error.

I also develop this connection for Bitbucket and there I found out that this function is no longer allowed via Oauth. Maybe this is similar to Github.

**Comment by acrobat** [comment]
This is what the [github documentation](https://developer.github.com/v3/users/keys/#create-a-public-key) mentions
> Requires that you are authenticated via Basic Auth, or OAuth with at least `write:public_key` scope.

So it should work through oauth. Check if you have permission for that required scope. It seems that [github returns a 404](https://developer.github.com/v3/troubleshooting/#why-am-i-getting-a-404-error-on-a-repository-that-exists) for issues with the authenticated user scopes.

Please double check those mentioned requirements. I'm closing this issue for now, please let us now if there is a bug in this library so we can reopen the issue. Thanks!
