### ISSUE TITLE
Can be used without Composer

### ISSUE THREAD

**Issue by BennyChange** [KnpLabs/php-github-api#798]
Is it possible to use the API without Composer?

**Comment by GrahamCampbell** [comment]
Technically yes, but you wouldn't want to. You'd have to recursively download all the dependencies yourself and then use an autoloader... probably composers... So you should absolutely just use composer. If you don't want to globally install it on your system, that's OK, just have the phar with your project if you really want.

**Comment by acrobat** [comment]
As @GrahamCampbell explained it should be possible (with a lot of extra manual work), but is not all advised. Please try/use the composer install method.
