### ISSUE TITLE
Accept header not set for Apps API

### ISSUE THREAD

**Issue by adhikasp** [KnpLabs/php-github-api#800]
Apps endpoint should have `application/vnd.github.machine-man-preview+json` header.

It seems that `class Apps extends AbstractApi` doesn't override `configure()` method yet.

**Comment by acrobat** [comment]
It seems that the header was removed in #592 but it [should still be set](https://developer.github.com/changes/2017-05-22-github-apps-production-ship/#how-can-i-try-it). Can you create a pr to automatically set the required header on each call?

See [example here](https://github.com/KnpLabs/php-github-api/blob/8c26dc85f732cc6b426bd85af4cf18bdfcdb20ff/lib/Github/Api/Repository/Checks.php#L35-L36)
