### ISSUE TITLE
Update requirements from php-http to psr

### ISSUE THREAD

**Issue by Taluu** [KnpLabs/php-github-api#810]
As PSR-18 was passed some months ago, maybe instead of requiring `php-http/client-implementation`, requiring `psr/http-client-implementation` (not sure of the name) would be more appropriate ?

**Comment by Nyholm** [comment]
That would be a BC break. However, all clients implementing `psr/http-client-implementation` should also (easily) implement php-http/httplug:2.0. We will support HTTPlug 2.0 in #802

**Comment by acrobat** [comment]
Closing this issue as @Nyholm stated, all clients implement the psr client implementation and since #802 (v2.12.0) we have support for httplug 2.0
