### ISSUE TITLE
Deprecation Notice - Authentication

### ISSUE THREAD

**Issue by andre-paulo98** [KnpLabs/php-github-api#837]
Recieved a email few days ago that the Authentication Method I was using would be deprecated soon:
![image](https://user-images.githubusercontent.com/19685105/71021800-028c9500-20f7-11ea-9b71-77c503b96a7f.png)
I was using `$client->authenticate("my@email.com", "my_password", \Github\Client::AUTH_HTTP_PASSWORD);`
I went ahead and created a Personal Access Token, changed the code and ended up with this:
`$client->authenticate("my_PAT", "", \Github\Client::AUTH_HTTP_TOKEN);`
Is this going to use the right endpoint, and not the one that is gonna be deprecated?
It seems to be working fine, but just wanna be sure.

**Comment by GrahamCampbell** [comment]
>  Is this going to use the right endpoint, and not the one that is gonna be deprecated?

The email doesn't say the endpoint is deprecated, it says using basic authentication with a password is deprecated. Basic authentication using a token is fine.

**Comment by GrahamCampbell** [comment]
This issue can be closed @acrobat. :)
