### ISSUE TITLE
Creating review with wrong commit ID crashed exception thrower

### ISSUE THREAD

**Issue by olivernybroe** [KnpLabs/php-github-api#848]
When creating a review which has a commit ID which is not part of the PR, the exception thrower crashes, as there are no code field in the errors array from GitHub.

This is the data from GitHub
```
array:3 [
  "message" => "Unprocessable Entity"
  "errors" => array:1 [
    0 => "End commit oid is not part of the pull request"
  ]
  "documentation_url" => "https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review"
]
```

**Comment by acrobat** [comment]
@olivernybroe what do you mean with “crashes”? And what is the http code github returns for this call?

**Comment by olivernybroe** [comment]
I gives a 422 back. 

It fails on this line
https://github.com/KnpLabs/php-github-api/blob/d404193c0c1772e3e5b101b49633ad1d9b4ab1e1/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php#L54-L59
because `errors` array does not have a `code` property.

**Comment by acrobat** [comment]
I've tried to reproduce this but I was not able to do so. When passing an invalid commit hash, this api added the comment to the latest commit without any errors. 

I'm closing the issue for now. If this still occurs or you have a clear reproducer, please leave a comment and/or reopen the issue.
