### ISSUE TITLE
Phpstan coverage

### ISSUE THREAD

**Issue by staabm** [KnpLabs/php-github-api#857]
Would you accept a PR adding a travis job for phpstan?

... and additional PRs to introduce more specific typehints, e.g. more concrete array return-types etc 

see https://github.com/KnpLabs/php-github-api/blob/94dec1e3753fd9c28aaddba3985db011e445bde0/lib/Github/Api/Issue/Labels.php#L25

This would ease usage of the lib and allow to find errors faster when using it in a upstream project

**Comment by acrobat** [comment]
@staabm any initiative to improve the overall code quality is a good idea! If you want to start working on this, that would be great. I would suggest to open a PR to add this to our test suite with the lowest phpstan level, from there on we can move slowly to the higher levels!

**Comment by staabm** [comment]
cool, just wanted to get in touch with you first.

I will get a developer assigned

**Comment by staabm** [comment]
it seems @danielplatt-clx is working on it

**Comment by platt-website** [comment]
Hello :) Like @staabm wrote, i'm currently working on the PHPStan integration with my private github profile (not @danielplatt-clx). When I'm ready i will create a PR and contact you.
