### ISSUE TITLE
The Repo Labels `update` method is incorrect

### ISSUE THREAD

**Issue by bobeagan** [KnpLabs/php-github-api#859]
https://github.com/KnpLabs/php-github-api/blob/94dec1e3753fd9c28aaddba3985db011e445bde0/lib/Github/Api/Repository/Labels.php#L36

The actual parameter should be "new_name" and all parameters are optional to include.
https://developer.github.com/v3/issues/labels/#parameters-1

Additionally, the Repo Labels appears to be missing a related documentation page.

**Comment by acrobat** [comment]
@bobeagan Thanks for reporting this issue! Can you create a PR to fix the param and maybe a docs entry? Thanks!

**Comment by bobeagan** [comment]
@acrobat PR ready for your review

**Comment by bobeagan** [comment]
Hoping for a patch fix to be pushed to packagist after this gets merged so I can make use of it in my project without workarounds :)
