### ISSUE TITLE
Remove "shadow-cat" preview header

### ISSUE THREAD

**Issue by acrobat** [KnpLabs/php-github-api#869]
https://developer.github.com/changes/2020-04-07-graduated-previews/#shadow-cat-preview-graduates

**Comment by GrahamCampbell** [comment]
Done in https://github.com/KnpLabs/php-github-api/pull/888.

**Comment by GrahamCampbell** [comment]
Version for 2.x: https://github.com/KnpLabs/php-github-api/pull/893.
