### ISSUE TITLE
Delete revisions from gist

### ISSUE THREAD

**Issue by Dibbyo456** [KnpLabs/php-github-api#876]
I have gist which gets updated every 3 hours automatically, but github is tracking the revisions.
How do I delete revisions from gist? or instruct Github not to keep track?

**Comment by acrobat** [comment]
[The github api](https://developer.github.com/v3/gists/) doesn't have endpoints to delete revisions. My guess that it's because a revision is "commit" so deleting those would not be possible and it seems that deleting revision in the interface is also not possible.
