### ISSUE TITLE
Missing header in `/user/installations` requests

### ISSUE THREAD

**Issue by vovayatsyuk** [KnpLabs/php-github-api#882]
These two methods need a `application/vnd.github.machine-man-preview+json` header: https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/CurrentUser.php#L187-L206

Here is a new requirement: 
https://developer.github.com/v3/apps/installations/#list-app-installations-accessible-to-the-user-access-token
https://developer.github.com/v3/apps/installations/#list-repositories-accessible-to-the-user-access-token

> Note: To access the API with your GitHub App, you must provide a custom media type in the Accept Header for your requests.
>
> `application/vnd.github.machine-man-preview+json`

I can create a PR and move the methods to [Apps.php](https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/Apps.php) which already has a method to add required header, or I can copy [AcceptHeaderTrait](https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/Apps.php#L12-L17) to the CurrentUser class.

How do you want to fix it?

**Comment by acrobat** [comment]
@vovayatsyuk Can you add the `AcceptHeaderTrait` to the `CurrentUser` api class and set the acceptHeader property in each method. See the proctection api forexample.

https://github.com/KnpLabs/php-github-api/blob/0ce1f0934724db9d244c9fac1e2871361f0a03c4/lib/Github/Api/Repository/Protection.php#L35-L41
