### ISSUE TITLE
Make the next release from master 3.0.0

### ISSUE THREAD

**Issue by GrahamCampbell** [KnpLabs/php-github-api#887]
This is not technically necessary, however some might argue the change that has just gone into master is breaking. We could use this opportunity to also clean up some things from the code such as removing the deprecated authentication stuff, and changing out the `HttpMethodsClient` with `HttpMethodsClientInterface`.

There's no reason why a major release needs to mean big changes. Just some nice cleanup. ;)

**Comment by GrahamCampbell** [comment]
There's actually quite a bit of deprecated stuff accruing that could be removed.

**Comment by GrahamCampbell** [comment]
@acrobat I think the `v3-dev` branch can be deleted now, in favour of `master`.

**Comment by acrobat** [comment]
Yes indeed, there was no difference between those branches. v3-dev is removed!
