### ISSUE TITLE
Caching on a per file basis 

### ISSUE THREAD

**Issue by joshbruce** [KnpLabs/php-github-api#905]
Hello. First time user of this library (and a sophisticated interaction with GitHub API) and not sure I've seen the explicit answer.

Re caching I'm curious if that's on modification date of a specific file or the repo as a whole??

The GitHub API docs seem to point to the whole repo. The ability to path down to a specific file seems like it would be possible.

Just curious. Thanks.

**Comment by GrahamCampbell** [comment]
Yep, this can be done, and without any effort from you, so long as you have a PSR-15 cache adapter lying around. ;)

When you a Github/Client you have the option to pass a client builder to the constructor. You should take up the offer, and provide one, and add a cache plugin to it. 🚀

Here's an example:

```php
/** @var \Psr\Cache\CacheItemPoolInterface $psrCache */

$builder = Gitlab\HttpClient\Builder();
$builder->addCache($psrCache);

$client = new Gitlab\Client($builder);
$client->authenticate(/** do your thing */);

// Make your api call, and it will automatically be cached, varying on the authentication header.
// Next time you make the same call, we will send the standard caching headers inc. etags if
// GitHub provided them, and GitHub's servers will send us a not modified response back with
// no body if there's been no changes. We then go fetch from the cache without you lifting a finger!
$client->...
```

**Comment by GrahamCampbell** [comment]
If you wanna read the content of a certain file, the last line in that example would look like, for example:

```php
$client->repository()->contents()->show('KnpLabs', 'php-github-api', 'lib/Github/Client.php');
```

**Comment by GrahamCampbell** [comment]
NB Under the hood, this works using ETAGs, for the most part: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#conditional-requests.

**Comment by joshbruce** [comment]
Ah!

> If the resource has not changed, the server will return a 304 Not Modified.

This is where I got confused, I think. "Resource" in this context could be the repo as a whole or a single file?? Almost like it will be the most recent modified date of whatever's in the query results??

Probably going to use this one as I'm using a file-based approach: "cache/filesystem-adapter": "^1.0" - believe it meets the requirements.

**Comment by GrahamCampbell** [comment]
Resource, in that context, is the full URI.

**Comment by GrahamCampbell** [comment]
So neither the repo, nor the file. It is the abstract concept of what the URI represents.

**Comment by joshbruce** [comment]
Gotcha! Thanks. You're awesome.
