### ISSUE TITLE
Cache not generating files

### ISSUE THREAD

**Issue by joshbruce** [KnpLabs/php-github-api#909]
I created a very basic setup for caching - and made sure it worked. Put test in place - that apparently were fragile.

Moved stuff around and updated to GraphQL.

I don't get any files showing up in the cache directory.

Am I missing a step or call somewhere?

Client:

```php
use League\Flysystem\Adapter\Local;
use League\Flysystem\Filesystem;
use Cache\Adapter\Filesystem\FilesystemCachePool;

        if ($this->client === null) {
            $this->client = new Client();

            if ($this->useCache) {
                $adapter = new Local($this->cacheRootPath); // disk
                $filesystem = new Filesystem($adapter);
                $pool = new FilesystemCachePool($filesystem, $this->cacheFolderName); // subfolder
                $this->client->addCache($pool);
            }

            $this->client->authenticate($this->ghToken, null, Client::AUTH_ACCESS_TOKEN);
        }
        return $this->client;
```

Query and call:

```php
        $query = <<<'QUERY'
        query ($owner: String!, $repo: String!, $path: String!) {
          repository(owner: $owner, name: $repo) {
            object(expression: $path) {
              ... on Blob {
                text
              }
            }
          }
        }
        QUERY;
        $vars = [
            "owner" => $this->ghUsername,
            "repo" => $this->ghRepo,
            "path" => $this->parts()->countIsGreaterThan(0, function($result, $parts) {
                return ($result->unfold()) ? "master:". $parts->join("/") : "master:";
            })
        ];
        $response = $this->client()->api("graphql")->execute($query, $vars);
```

Pretty sure this first started when I switched to GraphQL. Could be wrong.

Will try to set up another project to see what's up as well - just checking if I missed something obvious.

- Checked permissions on the containing folder - 755, 775, and 777 - still no files. (Didn't need to do anything special on that score before GraphQL.)

**Comment by GrahamCampbell** [comment]
GraphQL doesn't support HTTP caching.

**Comment by joshbruce** [comment]
Ah. Ok. Good to know. Thanks for saving me time there.

Using HTTP, is there a way to get a list of files and folders in the repo?? 

Everything I've seen points to GraphQL

**Comment by GrahamCampbell** [comment]
Yes, the code I already gave you from the last issue will list the files if the path you provide is a directory, rather than a file. See the docs at https://developer.github.com/v3/repos/contents/#get-repository-content. :)

**Comment by GrahamCampbell** [comment]
There's also https://developer.github.com/v3/git/trees/#get-a-tree, which is probably implemented here too.

**Comment by joshbruce** [comment]
rofl - All right, fair enough. Still getting used to the library and apparently not reading as well as I should. Thanks as always!
