### ISSUE TITLE
How to get the request header, request parameters, and response parameters?

### ISSUE THREAD

**Issue by JeffreyBool** [KnpLabs/php-github-api#914]
How to get the request header, request parameters, and response parameters? 
Is there no debug mode?

**Comment by lexor** [comment]
You can use `getLastResponse()` method for this case.

```
$headers` = $githubClient->getLastResponse()->getHeaders();
```

Reference: https://github.com/KnpLabs/php-github-api/blob/2.x/doc/request_response_info.md

**Comment by acrobat** [comment]
Thanks for the soluton @lexor! @JeffreyBool the snippet above should solve your problem!
