### ISSUE TITLE
api('search')->commits('repo:octocat/Spoon-Knife+css')

### ISSUE THREAD

**Issue by JeffreyBool** [KnpLabs/php-github-api#916]
![image](https://user-images.githubusercontent.com/24415888/89373621-c2c4fd00-d71b-11ea-83fb-c3f9f483b45b.png)

参数编码格式有问题，导致获取资源失败

**Comment by acrobat** [comment]
Hi @JeffreyBool, Can you report your issue in english please? What is the exact problem that you're experiencing?

**Comment by JeffreyBool** [comment]
There is a problem with the parameter encoding format, resulting in the failure to obtain resources

**Comment by JeffreyBool** [comment]
![image](https://user-images.githubusercontent.com/24415888/90207520-0bb23b00-de19-11ea-9092-7c9827cc566f.png)
The plus sign has been escaped

**Comment by acrobat** [comment]
@JeffreyBool can you try the 2.x branch if it fixes your problem? It contains a fix for building query parameters (see #908)

**Comment by acrobat** [comment]
No more feedback received. If this is still an issue, please open a new issue with a clear explanation and reproducer.
