### ISSUE TITLE
Allow Guzzle 7

### ISSUE THREAD

**Issue by freekmurze** [KnpLabs/php-github-api#919]
Is there a way to use this package in combination with Guzzle 7?

**Comment by acrobat** [comment]
@freekmurze There is already work done by @GrahamCampbell in the master branch (upcoming 3.0) to support guzzle 7.

See https://github.com/KnpLabs/php-github-api/blob/master/README.md#install

**Comment by freekmurze** [comment]
Ah nice! @GrahamCampbell seems to be everywhere 🙂

**Comment by GrahamCampbell** [comment]
These are the relevant PRs, which enable this package to work with Guzzle 7: https://github.com/KnpLabs/php-github-api/pull/885, https://github.com/KnpLabs/php-github-api/pull/888, https://github.com/KnpLabs/php-github-api/pull/910.

**Comment by GrahamCampbell** [comment]
@acrobat Do you need any help preparing the 3.0.0 release?

**Comment by acrobat** [comment]
I wanted to refactor the code more and deprecate more stuff but I don't have much time for the moment. So I will try to go through the last open PR's for 3.0 (I think the main PR will be your immutable pager PR) and have a release ready soon!

**Comment by hotmeteor** [comment]
Any update on this?

**Comment by acrobat** [comment]
I'm reviewing #907 and we need to finish that PR. I'm trying to push some more changes into 3.0 but if #907 get's finished before I get time for those extra changes these will be postponed to 4.0.

**Comment by jljr222** [comment]
Hi all,

Is this still in the works? I'm in need of Guzzle 7 support for my next project. I tried to run:

`composer require knplabs/github-api:^3.0 guzzlehttp/guzzle:^7.0.1 http-interop/http-factory-guzzle:^1.0`

Didn't work because v3.0 doesn't exist yet. I tried "3.0.x-dev" and that also did not work. Is there a way to install 3.0 in its current form?

**Comment by GrahamCampbell** [comment]
Just add the relevant entries manually to your composer.json file and run composer update. composer require is limited in its capability, and use `^3.0@dev` rather than `^3.0`.

**Comment by jljr222** [comment]
That worked great, thank you. I'm just getting started with composer, so a lot of it is new to me. Appreciate it 👍🏽

**Comment by acrobat** [comment]
[3.0.0](https://github.com/KnpLabs/php-github-api/releases/tag/v3.0.0) was released yesterday, this version is compatible with psr18 clients and guzzle 7. Enjoy! 🎉
