### ISSUE TITLE
How to check if a branch exists in a repository?

### ISSUE THREAD

**Issue by ppshobi** [KnpLabs/php-github-api#923]
Sorry if it's totally noob level, Title explains all.

**Comment by acrobat** [comment]
Hi @ppshobi,

We use this issue tracker to keep track of bugs and features/feature requests. For help on implementing the api you should check [our docs](https://github.com/KnpLabs/php-github-api/blob/2.x/doc/README.md) and/or the [github api docs](https://docs.github.com/en/free-pro-team@latest/rest).

For this specific case you can use the [get branch endpoint](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-a-branch) as it will return a 404 when the branch is not found. See also: https://github.com/KnpLabs/php-github-api/blob/2.x/doc/repos.md#get-single-branch-of-a-repository
