### ISSUE TITLE
Is it possible to download a release via the API?

### ISSUE THREAD

**Issue by jljr222** [KnpLabs/php-github-api#926]
There is a download method for repo contents, but do not see anything like that for releases. I have a private repo I am trying to get the release and download via cURL. I may not be using the API correctly, so apologies if this is not an API question. I just wanted to make sure I wasn't missing something.

Thank you!

**Comment by acrobat** [comment]
Hi @jljr222 

This issue tracker is used to report bugs and feature requests, so I would refer to our and the github docs for questions on how to use the api.

In this case you can use the releases endpoint to get a release asset, see [our docs](https://github.com/KnpLabs/php-github-api/blob/2.x/doc/repo/assets.md#list-one-asset) and the [github docs](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-a-release-asset)
