### ISSUE TITLE
Allow PHP 8

### ISSUE THREAD

**Issue by petr-buchin** [KnpLabs/php-github-api#943]
For now I cannot install this library using PHP8 (or I must use `--ignore-platform-reqs` flag for `composer install`).
Could you please allow PHP8 version in `composer.json`?

**Comment by GrahamCampbell** [comment]
That is correct. Either use `--ignore-platform-req=php` or try out `^3.0@dev`, which already supports PHP 8. It's release is not far off now.

**Comment by acrobat** [comment]
PHP8 support is now available in the [3.0.0 release](https://github.com/KnpLabs/php-github-api/releases/tag/v3.0.0)
