### ISSUE TITLE
[4.x] [RFC] Drop `ResultPagerIterface::postFetch`

### ISSUE THREAD

**Issue by GrahamCampbell** [KnpLabs/php-github-api#951]
I think we should remove `postFetch` from the result pager interface and make the function private on the result pager. What use case is there for calling it from the outside?

**Comment by GrahamCampbell** [comment]
We could also make classes like `ResultPager` and `ResponseMediator` final.

**Comment by acrobat** [comment]
I will make a PR to mark those classes as final, that's indeed a good idea! I also don't see a direct usecase for the postFetch method, so maybe deprecate it in 3.1 and have it removed in. 4.0. This will give users time to report valid usecases for this method, also keeping the method in for now doesn't really do any harm or increased maintenance.
