### ISSUE TITLE
"Authenticating as an Integration" doc is out of date

### ISSUE THREAD

**Issue by amacrobert-meq** [KnpLabs/php-github-api#952]
Documentation in `/doc/security.md` is out of date.

1. The code example references the lcobucci/jwt library, but no version number. Using the latest version of that package with the given code example results in an error (cannot instantiate an interface "Builder").
2. When using the latest compatible version of lcobucci/jwt, there are 2 deprecated warnings.

I will submit a PR to fix these shortly.

**Comment by amacrobert-meq** [comment]
I see now that I edited the code, the link to lcobucci/jwt was to a specific version for which the example code presumably works (wish I had used that link when setting up the first time).

So although fixing this is probably unnecessary, my PR at least removes some ambiguity and supports a more recent version of the library.

**Comment by acrobat** [comment]
Fixed in #953
