### ISSUE TITLE
Get repo by topic/tag

### ISSUE THREAD

**Issue by samety-dev** [KnpLabs/php-github-api#960]
Hello,
how to get repo by topic/tag

**Comment by acrobat** [comment]
Hi @samety-dev, you can use the search api enpoint for this. See [our docs](https://github.com/KnpLabs/php-github-api/blob/master/doc/search.md#search-repositories) (and [github docs](https://docs.github.com/en/github/searching-for-information-on-github/searching-topics#search-repositories-by-topic) for more info on the query syntax)
