### ISSUE TITLE
How to authenticate a user the Github Apps?

### ISSUE THREAD

**Issue by glebstar** [KnpLabs/php-github-api#961]
I have a token and a nickname of the user github.
Through the console, I can authenticate the user like this:

`curl -i -u your_username:your_token https://api.github.com/user`

How do I authenticate a user through this library?

**Comment by acrobat** [comment]
Hi @glebstar,

You can use the `Github\Client::AUTH_ACCESS_TOKEN` auth method with an accessToken, see [the documentation](https://github.com/KnpLabs/php-github-api/blob/master/doc/security.md#supported-methods). Username:password authentication is deprecation by github an was removed as supported method in v3 of this library.

**Comment by glebstar** [comment]
@acrobat, thanks for the answer!
Give me an example how to do this?

**Comment by glebstar** [comment]
https://docs.github.com/en/rest/overview/other-authentication-methods#via-oauth-and-personal-access-tokens

**Comment by acrobat** [comment]
@glebstar The example is like it's described in the docs. So after creating the client call the `authenticate` method.

```php
$client->authenticate('PERSONAL_ACCESS_TOKEN', Github\Client::AUTH_ACCESS_TOKEN);
```

But can you test if this works correctly for oauth tokens? or if we need to introduce a new auth mode to provide username + token.

**Comment by glebstar** [comment]
@acrobat, Thanks, it works
