### ISSUE TITLE
Get workflow runs for a specific branch.

### ISSUE THREAD

**Issue by nextgenthemes** [KnpLabs/php-github-api#963]
https://docs.github.com/en/rest/reference/actions#list-workflow-runs-for-a-repository

Not sure if I read this right, but it sounds like I should be able to get workflow runs for a `branch` but I can't found out how I would be able to do this with this. Seems parameters are missing completely.

I am wondering why I am messing with this at all not try some PHP CURL directly. Why is this so complicated? Why does this need additional abstractions to build on top of it? Why does GitHub itself does not have an official PHP lib for this?

I guess I could use https://github.com/KnpLabs/php-github-api/blob/master/doc/request_any_route.md. I would not call this "Extensively Documented".

**Comment by lexor** [comment]
@nextgenthemes actually already implemented [this case](https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/Repository/Actions/WorkflowRuns.php#L21) on `all`, `show`, `listRuns` methods.

```php
$workflowRuns = $client->api('repo')->workflowRuns()->all('KnpLabs', 'php-github-api', [
    'branch' => 'foo',
]);
```

**Comment by nextgenthemes** [comment]
@lexor Not documented, AFAIK. Searched long and hard for the docs on this found them not linked, the last `$parameters` parameter is not documented at all for this. https://github.com/KnpLabs/php-github-api/blob/master/doc/repo/actions/workflow_runs.md

I even guessed there was maybe a one general way for each command to take parameters, searched for general docs on this and did not find anything. So again without the claim "Extensively Documented" I would not be mad about this ....

Should probably just look at the source in the first place. Ended up doing this, and that also works.

```php
		$response = $client->getHttpClient()->get("/repos/$user/$repo/actions/runs?branch=$tag");
		$data     = Github\HttpClient\Message\ResponseMediator::getContent($response);
```

**Comment by acrobat** [comment]
Hi @nextgenthemes, this is an opensource project so we are open for contributions to improve our code, docs, tests, etc. So I you find some parts of the documentation not clear, please open a PR to improve the docs for future users. I've created #964 to keep track of this.

That being said, the `$parameters` argument was indeed not documented so it can be improved. But to already provide some info on this array, you can pass all values of the type `query` that are supported by the github api in this array. See [the documented parameter list](https://docs.github.com/en/rest/reference/actions#list-workflow-runs-for-a-repository--parameters)

**Comment by acrobat** [comment]
The original issue/question is resolved. The documentation changes are moved to separate issues.
