### ISSUE TITLE
Accept header missing for the chceks API in 2.16.0 and newer

### ISSUE THREAD

**Issue by Agares** [KnpLabs/php-github-api#967]
I am using this package with GitHub Enterprise, version 2.22, when `knplabs/github-api` is at version 2.16.0, trying to use the checks API results in `Github\Exception\RuntimeException` (message: If you would like to help us test the Checks API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.). I don't see an obvious way to specify the header as a user of the library. 
Would it be possible to add it back, or add an option to pass custom headers to the checks calls?

**Comment by acrobat** [comment]
Hi @Agares, we've removed that header a time ago as github promoted the checks api to stable. See [their blogpost](https://developer.github.com/changes/2020-10-01-graduate-antiope-preview/) and I also can't find any info on the checks rest api docs.

Can you debug this issue a bit more and/or contact github support if the problem persists?

**Comment by Agares** [comment]
The checks API was promoted to stable for github.com, but for enterprise server it's still in preview (on 2.22, which is the newest stable version): https://docs.github.com/en/enterprise-server@2.22/rest/overview/api-previews#check-runs-and-check-suites-api

**Comment by acrobat** [comment]
Hmm good point, then we should indeed automatically set the header (or re-introduce the configure method) so enterprise users can user these endpoints again.

**Comment by Agares** [comment]
I believe the header being present when it's not needed does not hurt anything, so maybe easier to just add it unconditionally?

**Comment by acrobat** [comment]
Yes, good idea! Are you up for a PR to re-add the header?

**Comment by Agares** [comment]
sure! will work on that tomorrow
