### ISSUE TITLE
Method to create a repository using a template?

### ISSUE THREAD

**Issue by martinbean** [KnpLabs/php-github-api#976]
I’ve had a look through the repository, but struggling to find a method that does this API call:

https://docs.github.com/en/rest/reference/repos#create-a-repository-using-a-template

Does this exist within this library?

**Comment by acrobat** [comment]
Hi @martinbean! This endpoint is indeed not yet covered by our library. A pr to add this endpoint is welcome!

**Comment by martinbean** [comment]
@acrobat Great, thanks for confirming! Will look at contributing a PR for this in that case.

**Comment by martinbean** [comment]
@acrobat Just created a PR for this endpoint: https://github.com/KnpLabs/php-github-api/pull/994
