### ISSUE TITLE
Support etags to preserve rate limits

### ISSUE THREAD

**Issue by staabm** [KnpLabs/php-github-api#996]
Today I was reading this great GitHub engineering blog post https://github.blog/2021-04-05-how-we-scaled-github-api-sharded-replicated-rate-limiter-redis/

especially interessting was this paragraph:
> ... the current implementation doesn’t increment the “current” rate limit value until after the request is finished. We do this because we don’t charge clients for 304 Not Modified responses (this can happen when the client provides an E-Tag)

As I understood it, this means a request which brings a proper etag header with it, is not counted against the rate limit on a http 304 match. This seems like a great opportunity to preserve rate limits.

[Searching thru this repo](https://github.com/KnpLabs/php-github-api/search?q=etag&type=commits) I found a few old commits also mentioning this:  https://github.com/KnpLabs/php-github-api/commit/9e22b446e55cea8a2bfd088c8acfd01ca87776f0

It seems though that this feature was dropped later on (At least I was not able to find etag support ob the latest master version).

was support dropped intentionally? Anything a lib consumer could/should do to benefit from it easily? Or is this something the lib here could easily support?

thx for any input regarding this interessting topic

**Comment by acrobat** [comment]
Hi @staabm! The reason that class/functionality was removed is that we moved to httplug as the http integration. Now we use the [cache plugin provided by httplug](http://docs.php-http.org/en/latest/plugins/cache.html) to handle this logic. And the `not-modified` / `e-tag` should be handled by that plugin out of the box.

So if you follow the [caching docs](https://github.com/KnpLabs/php-github-api/blob/5c540ae71ae175e9763d8cabbea48fea387718b7/doc/caching.md#response-caching), everything should work correctly!
